commitizen-tools/commitizen

commitizen/cli.py
The break is not needed and it lead to config files not work.
=> fix: fix config file not working

commitizen/bump.py, commitizen/cli.py, commitizen/commands/bump.py, commitizen/defaults.py, docs/bump.md, docs/config.md, tests/test_bump_create_commit_message.py, tests/test_conf.py
=> feat(bump): new commit message template

CHANGELOG.md, commitizen/cli.py, commitizen/commands/commit.py, tests/test_cli.py, tests/test_commands.py
=> feat(commit): new retry argument to execute previous commit again

commitizen/commands/commit.py, commitizen/config.py, commitizen/cz/base.py, docs/config.md, tests/test_conf.py
=> make style configurable for commit command

commitizen/commands/commit.py, commitizen/git.py, tests/test_commands.py
* Abort `cz commit` it there is nothing to the commit
* The underhook git commit follows [cz-cli::src/commitizen/staging.js#L9](https://github.com/commitizen/cz-cli/blob/7c4703bb2afc8bbb8a910aa958a855cad2f6beb7/src/commitizen/staging.js#L9). Although in [cz-cli::src/cli/strategies/git-cz.js/#L51](https://github.com/commitizen/cz-cli/blob/26533fcff90544a4152009ad38f4f15f96e7fefd/src/cli/strategies/git-cz.js#L51), they provide a `--allow-empty`, it seems not necessary to me. What ddo you think?
#45
=> Abort if no change

pyproject.toml
Project can now be invoked as 'git cz'.
=> Fixes #60: Add 'git-cz' entrypoint in user's PATH.

commitizen/cz/__init__.py, commitizen/cz/customize/__init__.py, commitizen/cz/customize/customize.py, docs/config.md, docs/customization.md, scripts/test, tests/test_cz_customize.py
#54 
* Enable committing and bumping customization through `toml` file
* TODO: validators
=> Customize committing and bumping through toml file

commitizen/cli.py, commitizen/commands/commit.py, tests/test_commands.py
Generate a commit message without doing anything
closes #56
=> Fixes #56: feat(Commands/commit): add ´--dry-run´ flag to the Commit command

.github/workflows/bumpversion.yml, .github/workflows/pythonpublish.yaml, docs/tutorials/github_actions.md, scripts/deploy, scripts/publish
=> GitHub actions to bump and publish

commitizen/cli.py, commitizen/commands/__init__.py, commitizen/commands/check.py, commitizen/cz/__init__.py, commitizen/cz/exceptions.py, tests/test_bump_command.py, tests/test_commands.py, tests/test_cz_customize.py
**Bug**
AnswerRequiredException not caught
**Solution**
AnswerRequiredException inherits CzException
=> fix(cz/exceptions): Fix AnswerRequiredException not caught

commitizen/cli.py, commitizen/commands/__init__.py, commitizen/commands/check.py, commitizen/cz/__init__.py, tests/test_bump_command.py, tests/test_commands.py, tests/test_cz_customize.py
Currently, if --commit-msg-file is not provided, it throws exception
=> fix(commands/check.py): make --commit-msg-file a required argument for check command

commitizen/commands/bump.py, commitizen/config/base_config.py, commitizen/config/ini_config.py, commitizen/config/toml_config.py, commitizen/defaults.py, tests/test_conf.py
This PR is based #100 and should be reviewed after #100 is merged.
Related Issue: #82
* Use "version_files" internally, but users can still use "files" till the next release.
=> Rename files to version files

commitizen/cli.py, commitizen/commands/__init__.py, commitizen/commands/init.py, commitizen/config/ini_config.py, commitizen/config/toml_config.py, commitizen/git.py, docs/index.md, tests/test_commands.py
This PR is based #100 and should be reviewed after #100 is merged.
#57 
* Add init command for setup "name", "tag", "tag_format" when no config file exists.
=> Init command

scripts/publish
it's no longer needed due to the removal of mkdocs
#119
=> ci(scripts/publish): remove github_token check

.pre-commit-hooks.yaml, docs/check.md
Since `cz check` is needed only when committing, I set pre-commit check stage to commit-msg.
=> Set pre commit hook

commitizen/cz/conventional_commits/conventional_commits.py, tests/commands/test_check_command.py
Currently, if `cz check` is enforced, it bloack `cz bump`
=> [Fix] add "bump" into valid commit message in conventional commit

.pre-commit-hooks.yaml, docs/check.md
In the previous pre-commit PR, I add the wrong `stages` argument into the `.pre-commit-hooks.yaml`. It should be defined on the user side. I'll also update the document.
BTW, I notice it didn't bump the version and release on the previous PR.
=> Fix pre commit hook

commitizen/commands/init.py, commitizen/config/toml_config.py, commitizen/defaults.py, pyproject.toml, tests/test_conf.py
- fix clean up the file when initializing commitizen config
=> Fix init clean config file

commitizen/bump.py, pyproject.toml, tests/test_bump_find_increment.py
In the original design, MAJOR will be overwritten by other if it's not the latest one.
=> Hotfix for version bumping

commitizen/bump.py, commitizen/cli.py, commitizen/commands/__init__.py, commitizen/commands/bump.py, commitizen/commands/check.py, commitizen/commands/commit.py, commitizen/commands/init.py, commitizen/commands/list_cz.py, commitizen/commands/version.py, commitizen/config/__init__.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/cz/customize/customize.py, commitizen/factory.py, commitizen/git.py, pyproject.toml, scripts/lint, scripts/test, tests/commands/test_check_command.py, tests/test_conf.py, tests/test_cz_base.py, tests/test_cz_conventional_commits.py, tests/test_cz_jira.py, tests/test_cz_utils.py
* style: isort
* ci(scripts/test): add isort check to srctips/test
* ci(scripts/lint): move isort config to pyproject.toml
* feat(commands/check): add --rev-range argument for checking commits within some range
* refactor(cz/connventional_commit): use \S to check scope
* refactor(git): remove unnecessary dot between git range
#114
=> Batch check

docs/README.md, docs/check.md, docs/config.md, docs/customization.md, docs/tutorials/github_actions.md, docs/tutorials/gitlab_ci.md, docs/tutorials/writing_commits.md, mkdocs.yml, pyproject.toml
=> docs: update doc url due to moving from Woile/commitizen to commitizen-tools/commitizen

docs/customization.md
commitizen_cz_template is moved from Lee-W to commitizen-tools
=> docs(customization): update cookicutter template url

commitizen/cli.py, commitizen/commands/check.py
Currently, `cz check` without argument shows `One and only one argument is required for check command!` which does not give users a hint of how to fix it. Thus, this pr adds a "See 'cz check -h' for more information" after it.
=> Add help to check command

docs/README.md
=> docs(FAQ): add revert and chore types discussion

commitizen/bump.py, commitizen/defaults.py, scripts/test, tests/test_bump_find_increment.py
Default bump_map doesnt consider breaking change identificator "!". Regex keys should take care of it.
=> feat(find_increment): allow to use regex keys for bump_map

commitizen/config/__init__.py, commitizen/config/ini_config.py, tests/test_conf.py
=> fix(config): display ini config deprecation warning only when commitizen config is inside

docs/tutorials/github_actions.md
=> docs(tutorial/github_actions): suggest using pypi api token

commitizen/git.py, tests/test_git.py
GitCommit.message should return only title without excess newlines if commit body is empty.
=> fix(git): fix returned value for GitCommit.message when body is empty

docs/README.md, docs/third-party-commitizen.md
Add a new docs section for third-party contributed commit templates.
This way new templates do not need to be merged into the main codebase,
and instead exist as satellite repositories.
I wasn't exactly sure if you wanted all the third-party commit templates in the `README.md` itself, so I placed them inside a separate `docs` file instead.
See #158 for motivation.
=> docs(third-party): add third-party template documentation

docs/README.md, docs/contributing.md, mkdocs.yml
make contributing a separate page and add more instructions
=> Enhance contribute page

commitizen/cli.py, commitizen/commands/check.py, tests/commands/test_check_command.py, tests/test_cli.py
* Add explicitly deprecation warning category
* Add warning if no commit is found in `cz-check --rev-range`
=> Enhance warning

docs/config.md
There was some urls from previous documentation url
=> fix(docs): change old url woile.github.io to commitizen-tools.github.io

commitizen/cli.py, commitizen/commands/bump.py, docs/bump.md, tests/commands/test_bump_command.py
fix: #164
When we have in repo some pre-commit hooks, like black, mypy or anything like that
cz bump fails, even if pre-commit hooks passed.
it is strange as pre-commit write messages to sys.stdout.buffer not stderr...
example pre-commit config:
```
repos:
- repo: local
hooks:
- id: flake8
name: flake8
stages: [commit]
language: system
entry: poetry run flake8
types: [python]
exclude: setup.py
- id: mypy
name: mypy
stages: [commit]
language: system
entry: poetry run mypy
types: [python]
pass_filenames: false
```
This PR add optional --no-verify argument to bump command
=> feat(bump): add optional --no-verify argument for bump command

.github/workflows/bumpversion.yml, docs/tutorials/github_actions.md
fix: #157
skip only commits that startsWith: `bump:`
=> ci(github/bumpversion): fix workflow to not skip commits with bump word

commitizen/changelog.py, commitizen/commands/changelog.py, commitizen/commands/version.py, commitizen/cz/base.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/templates/keep_a_changelog_template.j2, docs/changelog.md, docs/customization.md, setup.cfg, tests/CHANGELOG_FOR_TEST.md, tests/commands/test_changelog_command.py, tests/test_changelog.py
=> feature: maps and hooks

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
* Initial GitHub template for issues
* Add detailed content to pull request template
* Create a pull request/issue
* Feature Request / Bug Report / Document should appear as options when creating an issue
* The template used in this pull request show be seen when creating a new pull request
=> Enhance GitHub template

.github/workflows/pythonpackage.yml, commitizen/bump.py, commitizen/changelog.py, commitizen/changelog_parser.py, commitizen/cli.py, commitizen/commands/bump.py, commitizen/commands/check.py, commitizen/config/__init__.py, commitizen/cz/base.py, commitizen/factory.py, commitizen/git.py, commitizen/templates/keep_a_changelog_template.j2, docs/tutorials/github_actions.md, pyproject.toml, scripts/test, tests/CHANGELOG_FOR_TEST.md, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/test_changelog.py, tests/test_cz_customize.py
(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)
* Refactoring
* unify docstring style to google convetion
* fix typo in codebase (through [codespell](https://github.com/codespell-project/codespell))
* fix
* remove trailing space in keep_a_changelog
* doc
* add pypa/gh-action-pypi-publish as reference
* ci improvement
* use `pydocstyle` to check docstring style
* add commit check
1. Generate changelog through `cz changelog`
The trailing space after each version should no longer exist.
#161
=> remove trailing space in keep_a_changelog and other minor improvement

commitizen/commands/init.py
I was trying out the commitizen init command when I noticed a typo in the word. Thought I would help fix this small typo 😀
=> style(init): fix typo in init script

pyproject.toml
Remove the `typing` dependency. The typing module is included in stdlib since Python 3.5.
=> Remove typing dependency

docs/README.md, docs/bump.md, docs/changelog.md, docs/customization.md
(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)
Add GitHub page link to README
1. `poetry run mkdoc serve`
2. Open `http://127.0.0.1:8000`
See a link to github page (`View full documentation`)
#196 
Add any other context or screenshots about the pull request here.
=> Add GitHub page link to readme

docs/customization.md
update title level for customization documentation
from
to
None
None
If applicable, reference to the issue related to this pull request.
Add any other context or screenshots about the pull request here.
=> docs(customization): update title level

.gitignore, docs/README.md, docs/contributing.md
Add instructions for pre-commit integration in the README.md itself. 
#196  #209
=> Precommit docs

docs/third-party-commitizen.md
**New template, with emojis!**
#214
=> 3rd-party new template

commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/commands/commit.py, commitizen/config/__init__.py, commitizen/git.py, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_commit_command.py, tests/test_conf.py
Only Running `cz commit`, `cz bump` and `cz changelog` in a non git project will raise NotAGitProjectError
Other commands like `cz --help` will work now
#206
(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)
**Describe what the change is**
1. Run `cz --help`, `cz ls`, `cz example`, `cz info`, `cz init`, `cz version`, `cz check`
2. Run `cz commit`, `cz bump`, `cz changelog` 
1. After running the first group (i.e. `cz --help `) of commands, no error should be raised.
2. After running the second group (i.e. `cz commit `) of commands, no error should be raised.
#206 
Add any other context or screenshots about the pull request here.
=> fix: Raise NotAGitProjectError only in git related command

commitizen/commands/bump.py
```sh
mkdir bump_test
cd bump_test
git init
cz init
touch some_file.txt
git add .
git commit -m "feat: added some_file"
cz bump --changelog
```
The `CHANGELOG.md` is added to git repo.
#221
=> fix(bump): add changelog file into stage when running `cz bump --changelog

commitizen/commands/init.py, tests/commands/test_init_command.py, tests/test_conf.py, tests/test_git.py, tests/utils.py
initial ".pre-commit-config.yaml" with cz hook through `cz init`
1. Run `cz init`. Choose "Y" for "Do you want to install pre-commit hook?"
1. A ".pre-commit-config.yaml" file with cz hook should  be created
#55
=> Setup pre-commit hook in "cz init"

pyproject.toml
=> fix: add missing `pyyaml` dependency

.github/pull_request_template.md
The current template has a lot of redundancy, the "Type of changes" are already specified on the commits, and the realted issues can be part of the additional context, this reduces the noise when filling the template.
1. Open a new pull request
2. Observe
=> docs: simplify pull request template

commitizen/git.py
this bug affects windows users, by adding a single quotation
in front of the tag
Closes #240
=> fix(git): use double quotation mark in get_tags

commitizen/commands/check.py, tests/commands/test_check_command.py
Update `cz check --rev-range` to show all ill-formatted commits when running batch checking
(Not sure if I need to add test case and update the docs)
All ill-formatted commits should be displayed when running `cz check --rev-range`
1. Go to any repo containing ill-formatted commits
2. Run `cz check --rev-range HEAD~10..HEAD` to check if all ill-formatted commits in the range is displayed (`HEAD~10..HEAD` could be replaced with any valid argument)
Solve Issue #175
=> feat(cz_check): Update to show all ill-formatted commits

.github/workflows/bumpversion.yml
Use [commtizen-action](https://github.com/commitizen-tools/commitizen-action) for bump version
Auto bump version after pull request is merged.
1. Merge pull request
=> ci(github-action): use commitizen github action

commitizen/cli.py, commitizen/commands/check.py, tests/commands/test_check_command.py
As mentioned in #200 , this PR make `cz check` can read a string input as an argument with "--message"
With "-m" or "--message", `cz check` checks string input as commit message.
1. `cz check -m COMMIT_MESSAGE`
2. `cz check --message COMMIT_MESSAGE`
Refer to issue #200
=> feat(cz_check): cz check can read from a string input

tests/commands/test_bump_command.py
Add different commit messages including major, minor, patch increment and optional scope in messages to bump command testing.
All test cases should pass as usual
Just running `pytest tests/commands/test_bump_command.py`
#127
=> Update bump test cases to add more different message pattern

.github/workflows/bumpversion.yml
Use personal access token instead of github token, in order to trigger new events (like pthonpublish)
=> ci(github-action): use personal access token

commitizen/commands/check.py, docs/auto_check.md, docs/check.md, tests/commands/test_check_command.py
As mentioned in #200, this PR makes `cz check` can read message from pipe. In this mode, "--message" option is used.
String input from pipe can be read by `cz check`
1. `echo COMMIT_MESSAGE | cz check`
2. `cat COMMIT_FILE | cz check`
#200 
This PR can't pass `./script/test`, because the test "test_check_conventional_commit_succeeds" in test_check_command.py failed. 
However, I don't understand why this test failed, because a similar test "test_check_jira_multiple_commands" succeeded.
I put a screenshot of the error message below
=> feat(cz_check): cz check can read commit message from pipe

commitizen/commands/bump.py, commitizen/commands/init.py, commitizen/exceptions.py, commitizen/git.py, tests/commands/test_bump_command.py, tests/test_git.py
… creating existing tag
raises NoneIncrementExit if `increment is None and new_tag_version == current_tag_version`
closes #280 
Not raising git fatal error (please see #280 )
1. commit a test, ci, build or doc w/ `cz c`
2. run `cz bump`
3. **no** fatal error will occur
=> fix(commands/bump): Add NoneIncrementExit to avoid git fatal error

commitizen/commands/changelog.py, commitizen/defaults.py, docs/changelog.md, tests/commands/test_changelog_command.py, tests/test_conf.py
As described in #291, this adds config options for the changelog arguments `--incremental` and `--start-rev` to commitizen.
* With `changelog_incremental = true` in the config file, commitizen will only ever attempt incremental changelog updates.
* With `changelog_start_rev = <rev>` in the config file, commitizen will always update the changelog starting from the given rev.
**changelog_incremental**
1. Add `changelog_incremental = true` to `pyproject.toml`/`.cz.toml`
2. add e.g. a custom preamble to the changelog
2. add changes and commit them as feat/fix
3. run `cz changelog`
4. have changelog updated and the preamble kept intact
**changelog_start_rev**
1. add changes and commit them as feat/fix
1. add changes and commit them as feat/fix and note rev
1. Add `changelog_start_rev = <rev>` …
=> Add changelog argument options

commitizen/commands/bump.py, commitizen/defaults.py, docs/bump.md, tests/commands/conftest.py, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/test_conf.py
As described in #290, this adds the ability to set `update_changelog_on_bump = true` in the config file, and Commitizen will automatically update the changelog when running `cz bump`, even if the `--changelog` flag is not added.
When setting `update_changelog_on_bump = true` `cz bump` will always update the changelog. When running `cz bump --no-changelog` that setting is overridden and the changelog is _not_ updated.
1. add `update_changelog_on_bump = true` to `pyproject.toml`/`.cz.toml`
2. add changes and commit them as feat/fix
3. run `cz bump`
4. have changelog updated _and_ version bumped
#290 
---
Let me know if you want any changes to be done to wording or implementation.
=> Add ability to create changelog on bump

.github/workflows/homebrewpublish.yaml, docs/README.md
Following the addition of commitizen to homebrew, I've updated the docs and added a Github Action.
The workflow depends on a [Personal Access Token](https://github.com/settings/tokens/new?scopes=public_repo) being made available for it.
Whenever a release is published, a PR should be sent to update the Homebrew formula.
N/A
Closes https://github.com/commitizen-tools/commitizen/issues/256
Github Action based on https://github.com/commitizen-tools/commitizen/issues/256#issuecomment-704182520 and [nef's workflow](https://github.com/bow-swift/nef/blob/master/.github/workflows/bump-formula.yml).
An example of nef's workflow being run successfully can be found [here](https://github.com/bow-swift/nef/actions/runs/181470176)
=> Homebrew Update

commitizen/bump.py, commitizen/cli.py, commitizen/commands/bump.py, docs/bump.md, tests/commands/test_bump_command.py, tests/test_bump_create_tag.py, tests/test_bump_find_version.py
This PR creates adds a new flag `--local-version` to the `bump` command that allows bumping the local version only instead of the public release. 
PS: I haven't create the tests/updated the documentation just yet. will do after confirmation the code is suitable. 
The current behavior of the `bump` ignores the [local version](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) and only bumps the public version. 
```shell
$ cz bump --files-only --yes
bump: version 2.6.0+3.0.0 → 2.7.0
```
This flag allows to bump only the local portion of the version like
```shell
$ cz bump --files-only --yes --local-version
bump: version 2.6.0+3.0.0 → 2.6.0+4.0.0
```
1. Specify the version with a local portion like `version = "5.6.0+0.0.1"`. 
2. Execute the bump with the flag …
=> feat(bump): add support to bumping local version

commitizen/commands/bump.py, docs/bump.md, tests/commands/test_bump_command.py
This PR allows the command `bump` with the flag `--files-only` to update the version in the configuration file and to create the changelog if the flag was passed. 
The current behavior exits the program before those 2 actions happen. 
- NA Add test cases to all the changes you introduce
The version in the configuration file will be updated and the changelog will be created (if flag passed) when using `bump --files-only`, changing the current behavior. 
1. run `cz bump --files-only --changelog`
2. check if the version was updated file `pyproject.toml` or `.cz.toml`. 
3. check if the changelog was actually created.
Related issue: #298
=> feat: allow files-only to set config version and create changelog

commitizen/commands/bump.py, tests/commands/test_bump_command.py
Closes #281
Described in the issue
This issue can only be triggered if there are commits but they are not elegible for an increment.
- let's say tag exists `0.1.0`
- a new commit is created "ci: update job name"
- `cz bumo -pr alpha` is executed
- commitizen will find commits, but no increment, thus triggering the bug that happens afterwards.
=> fix: prevent prerelase from creating a bump when there are no commits

docs/README.md
Adds missing links on README.md
=> docs(README.md): adds missing link

commitizen/cz/conventional_commits/conventional_commits.py, tests/commands/test_check_command.py
=> fix: support `!` in cz check command

commitizen/commands/init.py, commitizen/config/__init__.py, commitizen/config/json_config.py, commitizen/defaults.py, docs/config.md, docs/customization.md, tests/commands/test_init_command.py, tests/test_conf.py, tests/test_cz_customize.py
As mentioned in #120 , this PR add json support for configuration
Replace a TOML config file with a JSON config file with no side effects, (of course, passing the same arguments).
1. Run the tests
2. Activate the virtual environment provided by the project/Poetry
3. Since the json files are supported for configuration, try to add a new file called .cz.json to customize Commitizen.
Related to #120
=> Add json support for config

commitizen/cli.py, docs/README.md, pyproject.toml, tests/test_cli.py
As mentioned in #137 , this PR add auto-completion to cz using argcomplete
If the proper [activation](https://kislyuk.github.io/argcomplete/) is set, the auto-completion can performed just by pressing the 
tab key.
1. Run the tests
2. Activate the virtual environment provided by the project/Poetry
3. Activate the auto-completion. For one-time activation of argcomplete for Commitizen only, use: 
**$ eval "$(register-python-argcomplete cz)"**
4. Type incomplete commands and flags from Commitizen and just pres the tab key.
Related to #137
=> Provide shell completion for cz

commitizen/commands/init.py, commitizen/config/__init__.py, commitizen/config/yaml_config.py, commitizen/defaults.py, docs/config.md, docs/customization.md, tests/commands/test_init_command.py, tests/test_conf.py, tests/test_cz_customize.py
As mentioned in #314 , this PR add yaml support for configuration
Replace a TOML config file with a YAML config file with no side effects, (of course, passing the same arguments).
1. Run the tests
2. Activate the virtual environment provided by the project/Poetry
3. Since the yaml files are supported for configuration, try to add a new file called .cz.yaml or cz.yaml to customize Commitizen.
Related to #314
=> Add yaml support for config

commitizen/commands/commit.py
For multi user situation, it may get fail
```
Permission denied: '/tmp/cz.commit.backup'
``` 
The reason is another user has already created a temp file with the same name.
So if one user create temp_file should attatch with `$USER`  info to resolve permission issue
attach user info to temp-file name when $USER is possible
create `/tmp/cz.committom.backup`
=> fix(commit): attach user info to backup for permission denied issue

commitizen/commands/check.py
Encoding error will happen if commit-msg-file contains some language-specific chars (e.g. GBK?) in PyCharm
```text
File "c:\users\administrator\.cache\pre-commit\repofeq0u_vr\py_env-python3\lib\site-packages\commitizen\commands\check.py", 
line 64, in _get_commit_messages commit_msg = commit_file.read() 
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 76: illegal multibyte sequence [INFO] Restored changes from C:\Users\Administrator\.cache\pre-commit\patch1609311833.
```
and this problem causes by:
```python
with open(self.commit_msg_file, "r") as commit_file:
```
Just add `encoding='utf-8'`
Put some GBK text in `commit-msg-file` (e.g. 这是一段GBK文本).
I will add a test case if it is required.
=> fix: read commit_msg_file with utf-8

commitizen/changelog.py, commitizen/commands/changelog.py, commitizen/cz/base.py, commitizen/cz/customize/customize.py, commitizen/defaults.py, commitizen/exceptions.py, docs/customization.md, docs/exit_codes.md, pyproject.toml, tests/commands/test_changelog_command.py, tests/test_changelog.py, tests/test_cz_customize.py
Implements proposed feature in #319. The default change type order is `["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]` (in descending order of importance) followed by any other change types in alphabetical order. In the configuration file, a user can override this setting to specify their own order and cover custom change types of interest.
The `CHANGELOG` should be ordered in the user-specified order rather than FIFO
Run the standard pytest suite and see the two new test cases
Fixes #319
Example use: https://github.com/KyleKing/calcipy/commit/4a480a8ca91350c1a4c190a672af1e9d397a6eb2
=> feat(#319): add optional change_type_order

pyproject.toml, scripts/format, scripts/test
Fixes #325. Resolves errors from `./script/test` from `isort` by upgrading to `5.X` and using the new `profile = "black"`
```sh
❯ ./scripts/format; ./scripts/test
+ poetry run python -m isort commitizen tests
+ poetry run python -m black commitizen tests
All done! ✨ 🍰 ✨
67 files left unchanged.
========================================== test session starts ===========================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kyleking/Developer/Pull_Requests/commitizen, inifile: setup.cfg
plugins: mock-2.0.0, cov-2.10.1
collected 310 items                                                                                      
tests/test_bump_create_commit_message.py ...                                                       [  0%] …
```
=> build(#325): upgrade isort for black compatibility

docs/bump.md
Change in `bump` documentation. 
The flag in the CLI for tag format is `--tag-format` and not `--tag_format`.
=> docs(bump): update cli tag flag format

commitizen/config/yaml_config.py
=> fix: remove yaml warnings when using '.cz.yaml'

commitizen/commands/init.py, commitizen/git.py, tests/test_git.py
originally, we use "----------commit-delimiter----------" to split git command result and strip them which should be "\n----------commit-delimiter----------\n" instead.
Proceed as usual if users do not provide their email or commit message in their commit history
1. Create an empty project
2. `git init`
3. `touch test-file`
4. `git commit --author="Name <>" -m "whatever"`
5. `touch another-test-file`
6. `git commit --author="Name <>" -m "" --allow-empty`
#340
=> Fix git message parsing

docs/README.md
add PyPI download count per month to readme
1. `poetry run mkdocs build`
2. `poetry run mkdocs serve`
3. Go to http://127.0.0.1
=> add PyPI download count badge

docs/external_links.md, docs/faq.md
With this commit I will close https://github.com/commitizen-tools/commitizen/issues/251
I think some information in the docs is enough, no need for a new command
=> docs(faq): add new questions to faq

commitizen/changelog.py, setup.cfg, tests/commands/test_changelog_command.py
Support for multiline body, suppose a commit message like this:
```
fix: user issue
BREAKING CHANGE: this should be all picked up by commitizen itself, when
I do a new line like this, it will be included in the end result changelog
not this
```
Commitizen will detect a `fix` and a `BREAKING CHANGE`
both will be added to the changelog
1. Create a commit like the example above
2. Run `cz changelog`
3. Observe `cat CHANGELOG.md`
Closes #346
=> feat(changelog): add support for multiline BREAKING paragraph

commitizen/config/__init__.py, commitizen/config/base_config.py, commitizen/config/json_config.py, commitizen/config/toml_config.py, commitizen/config/yaml_config.py
=> fix(config): change read mode from `r` to `rb`

commitizen/git.py, tests/test_git.py
* fix(git): fix get_commits deliminator
* when we merge a pull request, it generates a commit without breakline
Changelog should be generated correctly
1. Run `cz ch` in commitizen (or any project that had merged pull request)
#315
=> fix(git): fix get_commits deliminator

commitizen/config/toml_config.py
Add utf-8 encode when write toml file.
Write toml file using binary mode.
Run `cz init` or `cz bump`.
#355
**Screenshots**
=> fix: add utf-8 encode when write toml file

docs/customization.md
`.cz.toml` is specified twice and gets confusing.
=> docs: remove duplicated file name

commitizen/bump.py, tests/test_bump_update_version_in_files.py
First thanks for this quite good project!
This is a rather confusing logic but I decided to send this PR as a way to start the conversation.
I am trying to use commitizen to bump rust projects and its default way works fine when bumping the version inside a `Cargo.toml` as usually, your own package's version is on the top. But if you have a lock file, rust also bumps the version there. This PR was done in a way to bump the version only after something is matched, in the example, I used the project name so the versions_file could have something like `Cargo.lock:version:project-name` where it only bumps version if the project name was found before it.
Bumping versions on `Cargo.lock` or any other file, should bump only the intended line.
Try to bump any Cargo.lock file or any file that can …
=> feat: Support versions on random positions

commitizen/config/toml_config.py, tests/commands/test_init_command.py, tests/test_conf.py
fix(commands/init): fix toml config format error
Run `cz init` without encountering error
1. Run `cz init` with [this `pyproject.toml`](https://github.com/py-plato/plato/blob/v0.1.0/pyproject.toml)
#367
=> fix(commands/init): fix toml config format error

commitizen/bump.py, tests/test_bump_update_version_in_files.py
This is a WIP to fix the current BREAKING CHANGE which includes the test that should pass. 
Because we don't want to bump, we should provide a fix of the breaking change.
In the meanwhile you can use commitizen<2.17.0
=> fix(wip): add test for current breaking change

commitizen/bump.py, tests/test_bump_update_version_in_files.py
As I've commented [here](https://github.com/commitizen-tools/commitizen/pull/372#discussion_r615275718) the bug fix that fixes my bug also introduces a new one.
If you have a file that has many `version = 1.0.9` and you bump to `1.1.10` every time you bump the version, the file increases 1 byte, and `re.findall` keeps a reference to the old string making every iteration point to a character back like (version, versio, versi, vers, and etc) to the point where it would move to previous likes and the check that makes sure that the current version is found on the current line fails.
All versions should be bumped no matter the size of the file and occurrences of a regex
1 - Have a file with at least 8 `version = 1.0.9` lines
2 - Bump version to `1.1.10` using `file:version` as the regex
#372 …
=> fix: fix multiple versions bumps when version changes the string size

commitizen/bump.py, tests/test_bump_update_version_in_files.py
Support updated versions in Docker Compose files.
- [-] Update the documentation for the changes
A version which is used to build a docker container should be usable to update a docker-compose.yaml file which is used to deploy that docker container. E.g. this is the case in an automated CI/CD setup using Amazon Elasticbeanstalk.
1. Create a docker-compose.yaml file where the version is used as tag for a docker file
2. Add docker-compose to the `version_files` config setting
3. Bump version
4. Check if the docker-compose file is updated
Related to issue #371
=> fix: version update in a docker-compose.yaml file

docs/changelog.md
fix typo in docs
cz ch --unreleased_version="v1.0.0"
usage: cz [-h] [--debug] [-n NAME]
{init,commit,c,ls,example,info,schema,bump,changelog,ch,check,version}
...
cz: error: unrecognized arguments: --unreleased_version=v1.0.0
=> fix docs typo

commitizen/cz/conventional_commits/conventional_commits.py, tests/commands/test_check_command.py, tests/test_cz_conventional_commits.py
Adjust schema_pattern in cz_conventional_commits to match the conventional_commits spec
- `cz -n cz_conventional_commits check -m "feat!(scope): message"` to fail validation
- `cz -n cz_conventional_commits check -m "feat(scope)!: message"` to pass validation
1. Check out this branch
2. Run commands as described in "Expected behaviour"
#381
=> Fix conventional commits schema pattern

commitizen/git.py, tests/commands/test_changelog_command.py, tests/commands/test_changelog_command/test_changelog_incremental_keep_a_changelog_sample_with_annotated_tag.md, tests/test_git.py
Closes #378
Both annotated and not annotated tags should work.
```
git clone https://github.com/Trim21/transmission-rpc.git
cd transmission-rpc
pip install -U commitizen
cz changelog
git tag -l
```
Now both annotated and not annotated are detected. If there's no `object` from an annotated, it means we have a lightweight tag.
Please also @Trim21 let me know if this patch works for you
=> fix(changelog): annotated tags not generating proper changelog

commitizen/defaults.py, docs/README.md, tests/commands/test_changelog_command.py, tests/commands/test_changelog_command/test_changelog_incremental_with_release_candidate_version_alpha_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_release_candidate_version_beta_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_release_candidate_version_rc_.md
Closes #357
Trying to create an incremental changelog after a prerelease failed.
This happened because of the version regex when parsing the changelog.
You'll see the changelog created
```
git init
cz init
git add .
git commit -m "chore: add config"
git tag 0.0.1
git commit -m "feat: first feat" --allow-empty
cz bump --prerelease rc --changelog
git commit -m "feat: second feat" --allow-empty
cz changelog --incremental
```
=> fix(changelog): generating changelog after a pre-release

pyproject.toml, tests/commands/test_changelog_command.py
=> fix: add support for jinja2 v3

commitizen/config/json_config.py
Output the json config as multi line instead of single-line.
This is much more readable.
Output should look like this:
```json
{
"commitizen": {
"name": "cz_conventional_commits",
"version": "0.0.1",
"tag_format": "$version"
}
}
```
=> fix: correct indentation for json config for better readability

docs/README.md
fix link to Customization in README.md
Check, that this URL is the correct one: https://commitizen-tools.github.io/commitizen/customization.html
=> docs(README): fix URL in README.md

commitizen/commands/commit.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/defaults.py, docs/config.md, docs/customization.md, tests/test_conf.py, tests/test_cz_conventional_commits.py
See the suggestion in #380.
- feat(prompt): add keyboard shortcuts with config option
> Also added chore option to conventional_commits choices
This PR adds a config option called `use_shortcuts` which enables shortcuts in conventional commit choices. It defaults to false, so it'd be opt-in for now. In #380, the suggestion was to add the `use_shortcuts: bool` kwarg to questionary.prompt in [commands/commit.py](https://github.com/zevisert/commitizen/blob/65eb4f8b53f2e050b5ddbafa4b32439ef2f1a13d/commitizen/commands/commit.py#L50), but questionary passes this on to every question, and subsequently throws for prompt types that don't support `use_shortcuts`. The solution was to add `use_shortcuts` to the first question in [cz/conventional_commits/conventional_commits.py](https://github.com/zevi …
=> Add keyboard shortcuts to prompt

docs/third-party-commitizen.md
Add documentation for the 3rd party module https://github.com/apheris/cz-github-jira-conventional
This addon extends the commitizen tools by:
- **require a Jira issue id** in the commit message
- **create links to GitHub** commits in the CHANGELOG.md
- **create links to Jira** issues in the CHANGELOG.md
=> docs: add docs for 3rd party module cz-github-jira-conventional

docs/tutorials/writing_commits.md
Resolve some minor typos and line up long line wrap point
1. Confirm readability and format of markdown meets your liking
=> docs: tutorial - address typos and layout

commitizen/git.py, tests/test_git.py
fixes #418
This part of the code was not originally tested, since changing the code did not break the existing tests. If interested, I could add tests for this with real git calls.
I did not add this to the documentation or README since it fixes a behaviour that was supposed to happen already.
=> fix(commit): correct the stage checker before commiting

docs/bump.md
I think it was a typo. In the example, the major and minor keyword were set in a strange order. I changed it to stay consistent with PEP
=> doc: inverse major and minor

commitizen/cli.py
argparse raises TypeError when non exist command is provided on Python < 3.9
but raise SystemExit with exit code == 2 on Python 3.9
this error does not break anything obviously from the user perspective, but will break our existing test
#429
This issue is caused by https://bugs.python.org/issue29298. The new checking is the correct one, but we'll need to keep the old one for backward compatibility. This fix was first introduced on [3.9.7](https://github.com/python/cpython/tree/v3.9.7) 👉 see [argparse.py#L730-L731](https://github.com/python/cpython/blob/v3.9.7/Lib/argparse.py#L730-L731)
detailed on #429 
detailed on #429
=> fix(cli): handle argparse different behavior after python 3.9

.github/ISSUE_TEMPLATE/bug_report.md, commitizen/cli.py, commitizen/commands/version.py, tests/commands/test_version_command.py
command to show system info output for bug reports
Issue #426
As mentioned in issue #426 , a single line command would be preferable to fetch system information
I added a `--report` flag to the `version` command for doing that.
System info can be output using a single command which can be attached to bug report
```bash 
commitizen version --report
```
=> feat(#426): system info utility

.github/workflows/pythonpackage.yml, pyproject.toml, tests/commands/test_check_command.py, tests/test_bump_find_version.py, tests/test_cli.py, tests/test_cz_conventional_commits.py
* style: format the code through the latest black
* build(poetry): update black version for python 3.9 and upgrade least support python version to python 3.6.2
* ci(github-actions):
* upgrade setup-python to v2
* add back 3.7 runner to pythonpackage
3.7 runner added when running checkings
send a pull request
=> ci(github-actions): add back 3.7 runner to pythonpackage

pyproject.toml
add typing_extension to prod dep as it's required in commitizen/defaults.py
error should no longer happen
1. `poetry install`
2. `poetry run python commitizen/defaults.py`
https://github.com/commitizen-tools/commitizen/issues/458
=> Add missing deps

commitizen/commands/check.py, docs/check.md, tests/commands/test_check_command.py
fix #455
Currently `cz check` will also check comment in git commit message (mentioned in issue #455). This PR add a filter to remove those comment lines in git commit message.
Comment in git commit message will be ignored.
1. Create a commit message file with comments in it (see #455)
2. Run `cz check --commit-msg-file <just_created_file>`
=> fix: filter out comment messege when checking

pyproject.toml
Changes the build backend from poetry to poetry_core. poetry_core is lighter weight than poetry and all that's required for the build vs project management aspect of poetry.
https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
>If your pyproject.toml file still references poetry directly as a build backend, you should update it to reference poetry-core instead.
=> build: use poetry_core to build instead of poetry

.github/workflows/pythonpackage.yml, pyproject.toml, tests/commands/conftest.py
Adds CI support for Python 3.10 and bump pytest to a version which is compatible with 3.10.
pytest 6.2.5+ is needed for Python 3.10: https://docs.pytest.org/en/6.2.x/changelog.html#pytest-6-2-5-2021-08-29
=> Support Python 3.10 in CI/local testing

docs/exit_codes.md
The source code indicates that the correct exit code is 3. See https://github.com/commitizen-tools/commitizen/blob/master/commitizen/exceptions.py#L10
Update the documentation with the correct exit number
The first three entries do not apply to this PR.
The documentation shows the correct information.
=> docs: Fix exit code for NoCommitsFoundError

docs/customization.md
Customising via the configuration file is clearly possible when using yaml files since you show an example for this. This PR updates the doc to remove the warning that states this is not possible. Given that yaml was the only missing file type in the original warning it seems safe to remove it completely.
- [n/a] Add test cases to all the changes you introduce
- [n/a] Run `./script/format` and `./script/test` locally to ensure this change passes linter check and test
- [n/a] Test the changes on the local machine manually
- [*] Update the documentation for the changes
N/A - Docs updated only
N/A - Docs updated only
N/A - Docs updated only
=> docs: removing customization file contradiction

commitizen/commands/bump.py, commitizen/exceptions.py, tests/commands/test_bump_command.py
See error in https://github.com/commitizen-tools/commitizen-action/issues/18
An error code should be returned when the bump can not succeed
Clone this repo https://github.com/now8-org/app
and run `cz bump`
1. Is there a reason why we weren't rising an error code in this situation? 🤔 
2. Am I missing any use case?
=> fix(bump): raise non zero error code when there's no elegible commit to bump

docs/faq.md
Addresses: #173
Add explanation for why the issue and PR for CalVer were closed
Please feel free to add comments or edit directly! I would be happy to make this more clear
=> docs: add Why not CalVer to FAQ

docs/config.md, docs/customization.md
Fix indentation on pages Configuration and Customization in online documentation.
Now it has mixed indentation (spaces&tabs) in some places. I replaced all tabs to eight spaces.
- [ X ] Update the documentation for the changes
Indentation for json in Configuration and Customization sections of docs contains only tabs or only spaces.
Old behaviour (unexpected change of:
=> docs(config.md,customization.md): Fix indentation (replace tabs (\t) with eight spaces)

commitizen/cz/__init__.py, tests/test_factory.py
When a package starting with a plugin name is found, but it is not a plugin, it becomes safely ignored.
When a packages has a name that matches a plugin, but it is not a plugin, it is safely ignored and reported to the user.
Background: The company where I work, and where I use `commitizen` for releasing package versions, is called CZ. And because we are not very imaginative, we use to call the packages that we develop for internal use something like `cz_`.
This collides with the way that `commitizen` discover plugins, and the discovery process raises an exception when a package starts with the name `cz_` is found but is not implemented as a plugin.
This MR proposes a way to ignore those packages that collide in name but are not plugins. This proposal tries to be as agnostic as possible, …
=> Safely ignore modules named `cz_` that are not plugins

commitizen/commands/check.py, commitizen/config/toml_config.py
Bitbucket add as default message when a pull request is merged, the message commit that starts with "Pull request". cz check fails with this kind of messages.
Signed-off-by: Angelo Mantellini <manangel@cisco.com>
Bitbucket add as default message when a pull request is merged, the message commit that starts with "Pull request". cz check fails with this kind of messages.
- [x ] Add test cases to all the changes you introduce
- [x ] Run `./script/format` and `./script/test` locally to ensure this change passes linter check and test
- [x ] Test the changes on the local machine manually
- [x ] Update the documentation for the changes
1. create commit that starts with "Pull request"
2. cz check
=> feat: skip merge messages that start with Pull request

commitizen/cli.py, commitizen/exceptions.py, commitizen/out.py, docs/README.md, docs/bump.md, docs/exit_codes.md, docs/tutorials/github_actions.md, tests/commands/test_bump_command.py, tests/test_cli.py
Closes #485
Exit code would rise 0 instead.
With no new commit run
```sh
cz --no-raise 3 bump
```
For more than one:
```sh
cz -nr 3 -nr 4 bump
```
- First implementation is just for numbers
- Docs should be updated
- It should support also a configuration parameter
=> feat: add --no-raise to avoid raising error codes

.github/pull_request_template.md, .pre-commit-config.yaml, commitizen/changelog.py, pyproject.toml, tests/commands/test_changelog_command.py
Ensure there is at least one blank line separating old and new content when appending incrementally to the changelog. Log entries for each release are already separated with blank lines, so separate pre-existing content from the first release with a blank line as well. If the pre-existing content ends with a blank line, then don't add an extra one.
I also fixed some unrelated pre-existing issues with `.pre-commit-config.yaml` in order to be able to comply with the contributing guidelines.
Please let me know which documentation I should update if you feel this change warrants mention. I wasn't sure whether to classify this as a tiny feature or a bug fix.
Closes #509.
If the changelog already says "This changelog is auto-generated by the Python-based …
=> Ensure At Least One Blank Line Between Old and New Changelog Content

.pre-commit-hooks.yaml, commitizen/commands/init.py, docs/README.md, docs/auto_check.md, tests/commands/test_init_command.py
Use new `--allow-abort` option. Prevent pre-commit hook from complaining when a commit is aborted by default, but allow users to override this option in their pre-commit config by specifying it in `args`, not `entry`. Move `--commit-msg-file` option from `entry` to `args` since it has to be the last option.
Confine hook to `commit-msg` stage. The Commitizen pre-commit hook runs `cz check`, which only makes sense to do on a commit message, not at other Git hook stages. By default the hook is currently run on staged files `pre-commit`, which is nonsensical unless the files in the repository themselves contain Git commit messages. The hook is an implausible candidate even for the `prepare-commit-msg` stage since this stage is intended for hooks that modify the commit message rather than …
=> fix(pre-commit): Correct pre-commit Hook Definition

commitizen/cli.py, tests/commands/test_bump_command.py
Use `str.upper` to pre-process the input of --increment
Support lower case arguments for the `--increment` option of the `bump` command.
```console
$ cz bump --increment patch
bump: version 0.6.1 → 0.6.2
tag to create: v0.6.2
increment detected: PATCH
```
Related:
- Closes https://github.com/commitizen-tools/commitizen/issues/533
=> feat(bump): make increment option case insensitive

commitizen/cz/conventional_commits/conventional_commits.py, tests/commands/test_changelog_command.py
This should fix duplicate entries in the changelog
Closes #510
Only entries that have a subject compliant with conventional commits should be included. 
Run on our own commitizen:
```
cz ch --dry-run 2.20.5..v2.21.0
```
Before it was including duplicated entries, now only good ones.
=> fix(changelog): skip non-compliant commit subjects when building changelog

commitizen/commands/check.py, commitizen/cz/conventional_commits/conventional_commits.py, tests/commands/test_check_command.py
Closes #449 
Currently the schema pattern of `cz` only checks the first line of commit message, so that some invalid format cannot be detected by `cz check`. I update the pattern to ensure there is a blank line between subject and body (if exists) and add some comments to make the regex a little more readable.
Meanwhile, because the inconsistent implementation of `Check._get_commits` for `--commit-msg-file` and `--message`, give a commit message file missing the blank line will also pass the validation (the missing line will be added by `Check`).
Miss blank line between subject and body will not pass `cz check`.
```bash
cat << EOF > /tmp/BAD_MSG                                                                                                                                          
ci: …
```
=> Make cz schema pattern more precise

commitizen/commands/bump.py, tests/commands/test_bump_command.py
This sends the changelog to stdout when paired with the `--dry-run` flag
when running `cz bump --changelog-to-stdout --dry-run`, the changelog should show in stdout
Closes #538
=> fix(bump): send changelog to stdout when `dry-run` is paired with `changelog-to-stdout`

commitizen/changelog.py
duplicate code exists in `changelog_parser.py`. 
This bit of code seemed to be unused/untested and contributing to lower overall code coverage.
=> refactor(changelog): removes unused code

commitizen/cmd.py, pyproject.toml
move from chardet to charset_normalizer to avoid recent issue on wrong encoding.
commitizen is able to decode command's strings without issue on `decode` .
https://github.com/commitizen-tools/commitizen/pull/545
https://github.com/commitizen-tools/commitizen/issues/544
=> refactor(tool): use charset_normalizer instead of chardet

commitizen/git.py
as title
pass all the test cases even when `LC_ALL` is set to non-English
1. `export LC_ALL=zh_TW.UTF-8`
2. `./script/test`
#542
=> use error_code to do "is_signed_tag" check to avoid language issue

tests/conftest.py, tests/utils.py
The unit tests were creating a bunch of keys (run tests a few times and see `gpg --list-keys`).
This solution creates a temporary `GNUPGHOME`. Notably gpg-agent requires a socket path of less 104 characters otherwise the gpg command will fail.
I am not confident this is the best approach but it is probably the easiest fix for the moment.
Is this a portable solution?
Also, I reduced the key length down to a debug level key for speed and security reasons.
no more added keys.
1. ran tests.
2. observed  `gpg --list-keys`
=> test(commands): stores gpg keyring in a temporary directory

pyproject.toml
=> chore: improve package classifiers

commitizen/cmd.py, commitizen/exceptions.py, docs/exit_codes.md, tests/test_cmd.py
Fixes #544 
Redo #545 
See issue #544: `cz` now creates the changelog without failing
=> fix(cmd): improve character encoding detection for sub-commands

.pre-commit-config.yaml, .pre-commit-hooks.yaml, docs/README.md
Check all commit messages on the current branch. This is useful for checking commit messages after the fact (e.g., pre-push or in CI) since the existing hook only works at commit time. Expand the documentation of the pre-existing commitizen hook to clarify the relationship between them. I wasn't sure whether it would be appropriate to add a section to [this documentation](https://commitizen-tools.github.io/commitizen/auto_check/).
Remove no longer needed `commit-msg` stage from self-use of `commitizen` pre-commit hook in `.pre-commit-config.yaml`. In v2.27.1, the `commitizen` pre-commit hook began specifying that it runs on the `commit-msg` stage in the hook definition in `.pre-commit-hooks.yaml`, so it is no longer necessary to specify the hook stage when using the hook in …
=> feat(pre-commit): Add commitizen-branch hook

tests/commands/test_changelog_command.py
=> test(changelog): fix datetime mocking error

commitizen/changelog.py, commitizen/commands/changelog.py, commitizen/exceptions.py, commitizen/git.py, docs/exit_codes.md, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_check_command.py, tests/test_git.py
`git.get_commits` could potentially fail silently. 
The first commit is the fix. 
See the git commit message for more info on all following commits (broken up for easier review). 
The final commit also improves error checking in `git.get_tags`  (closes #518).
Fail fast behavior and better reports to the user when something goes wrong with git.
Some of the tests showed the command was failing for unexpected reasons (e.g. invalid commit range `git log None..None`).
Without this change users with really old versions of git will see is "No commits found" but after the change: <b>
`GitCommandError: fatal: unrecognized argument: --author-date-order`
* reason:  `commands/changelog.py` calls `git.get_commits` with `--author-date-order`  but this argument is not valid for older versions of it. 
1. …
=> git.get_commits error check

commitizen/bump.py, pyproject.toml
Fixes #499.
The `version_files` feature uses a colon to delimit filenames from a regex to use to find the version. Make `version_files` slightly more robust by splitting on the first colon rather than all colons, thereby permitting the regex to contain a colon. Maintain the pre-existing assumption that the filename doesn't contain a colon, as this is rare and would likely cause many other problems.
Include colon in `version_files` regex. Commitizen runs bump on itself to, among other things, manage the version it uses of its own pre-commit hooks. When searching `.pre-commit-config.yaml` for the version number of Commitizen, look for `"rev:"` rather than `"rev"` to reduce the likelihood of a false positive now that colons are permitted in `version_files` regexes.
The version of the …
=> fix(bump): Support regexes containing colons

.pre-commit-config.yaml
Check existing commit messages. Use new `commitizen-branch` hook to verify correctness of existing commit messages post-commit and pre-push. This guards against cherry-picked commits with invalid commit messages as well as empty commit messages (e.g., created with `git commit --allow-empty-message`).
Run hooks pre-commit by default. They already run pre-push, and this behavior is left unchanged. Running hooks pre-commit gives developers more immediate feedback and improves commit quality by blocking an often unnecessary series of fix commits.
When testing this change locally, `poetry install` failed with the following error:
```
Creating virtualenv commitizen-9emEp_2F-py3.10 in ~/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: The lock file is not up to date …
```
=> Self Check With New `commitizen-branch` pre-commit Hook

commitizen/bump.py, pyproject.toml, tests/data/sample_cargo.lock, tests/test_bump_update_version_in_files.py, tests/test_bump_update_version_in_files/test_duplicates_are_change_with_no_regex.lock, tests/test_bump_update_version_in_files/test_random_location.lock
Fixes #498.
Add mypy typing for `_bump_with_regex`.
Avoid the complexities of multiline regex matching and inconsistencies with the case where no regex is specified. Simplify the implementation by eliminating the need to track an offset into the file. Ensure that the version number will be found even if it is to the left of the portion of the line matching the regex.
Remove lookahead assertion from `version_files` entry for `.pre-commit-config.yaml`. Commitizen runs bump on itself to, among other things, manage the version it uses of its own pre-commit hooks. When searching `.pre-commit-config.yaml` for the version number of Commitizen, we search for "Commitizen," which is in a comment to the right of the version number. Remove the lookahead assertion for "Commitizen," and instead simply …
=> fix(bump): Search for version number line by line

.pre-commit-config.yaml, commitizen/bump.py
Fixes #579.
Bump pre-commit hook self test from v2.32.2 to v2.32.3. The version of the Commitizen pre-commit hooks is typically bumped automatically by Commitizen itself, but because the behavior of `cz bump` was changed in Commitizen v2.32.3, and the bump from v2.32.2 to v2.32.3 was performed by Commitizen v2.32.2, the pre-commit hooks were not bumped.
Remove a redundant join call. The list of lines is now joined unconditionally in `_bump_with_regex`, so there is never a need to join it in `update_version_in_files`. The removed `join` was hence a no-op because it was performed on a `str`.
`cz bump` automatically increments the version of the Commitizen pre-commit hooks.
1. Run `cz bump` locally.
2. Confirm that the pre-commit hooks are automatically bumped from v2.32.3 to v2.32.4.
I …
=> Synchronize Pre-commit Hook Version with Commitizen Version

commitizen/commands/changelog.py, tests/commands/test_changelog_command.py, tests/commands/test_changelog_command/test_changelog_incremental_angular_sample.md
fix(command_changelog): Fixed issue #561 cz bump could not find the latest version tag with custom tag_format
- Updated args to _find_incremental_rev to use latest_tag_version instead of latest_version
- Updated test case for test_changelog_command.py from .next to .rc as python packaging lib doesn't take 'next' as a valid version
The changelog command will now use the tag_format_$version to lookup the git tags instead of just $version, which may fail if git tag has a long length which significally reduce the similarity
Configuration
```
$ cat .cz.toml | grep tag_format
tag_format = "SOME_TAG_PREFIX_$version"
```
Commits
```
$ git tag
SOME_TAG_PREFIX_1.0.0
$ git log
commit 11ba99fd2907be046e814662e3057c4bdd9f3db0 (HEAD -> master)
Author: Sam SIU <23556929+ssiuhk@users.noreply.github.com> …
```
=> fix(commands/changelog): Fixed issue #561 cz bump could not find the latest version tag with custom tag_format

commitizen/commands/bump.py
I notice that the the [commit command outputs both `stderr` and `stdout` of `git commit`](https://github.com/commitizen-tools/commitizen/blob/8cb1e22d72abd855f221556f2a1c8fc0ddded109/commitizen/commands/commit.py#L104). I am thinking it might be a good idea for the bump command to do the same. This way if there are any hook warnings it will show up in the bump output.
What do you think?
*  `cz bump --changelog` outputs: 
*  `scripts/test`
Helpful in diagnosing #520
=> fix(bump): log git commit stderr and stdout during bump

commitizen/bump.py, commitizen/cli.py, commitizen/commands/bump.py, docs/bump.md, tests/test_bump_find_version.py
This adds a `--devrelease` flag, expecting a non-negative integer, as per [PEP 440](https://peps.python.org/pep-0440/#developmental-releases); e.g. passing `--devrelease 1234` results in a developmental release segment of `.dev1234`.
When calling `cz bump`, passing `--devrelease`, followed by a non-negative integer will result in the bumped version adding a `.dev` suffix.
1. Check the existing behaviour: `python3 -m commitizen bump --dry-run`; for this branch, this gives `version 2.32.5 → 2.33.0`.
1. Check the new behaviour:  `python3 -m commitizen bump --dry-run --devrelease 0`; for this branch, this gives `version 2.32.5 → 2.33.0.dev0`.
See also discussions on #570.
=> feat: add functionality for dev-releases

commitizen/commands/bump.py, commitizen/git.py, tests/commands/test_bump_command.py
The elements in `version_files` may contain not only a file path, but also a regex after a colon. Thus make sure to only pass the file path to
`git add`.
Fixes a regression introduced in https://github.com/commitizen-tools/commitizen/commit/12b56ad6375bb116e6554b8771b27c7adbbc237f.
`CHANGELOG.md` gets `git added` and commited no matter what version files (+ regex) one specifies.
Before the following, broken, command was executed:
` git add CHANGELOG.md pyproject.toml:^version src/my_package/__init__.py:^__version__`
With this MR, the command looks like this:
`git add CHANGELOG.md pyproject.toml src/my_package/__init__.py`
Have the following commitizen settings in `pyproject.toml` file:
```toml
[tool.commitizen]
version = "1.0.2"
version_files = [
"pyproject.toml:^version",  # use regex to …
```
=> fix(bump.py): `CHANGELOG.md` gets git added and commited correctly

pyproject.toml
Closes #586 
Allow for installation of termcolor 2.x in commitizen enabled projects under Python >= 3.7
=> Conditionally relax specification for termcolor dependency

pyproject.toml, scripts/test
add commit check to our `./scripts/test`
run commit check when executing `./scripts/test`
1. `./scripts/tests`
=> ci(scripts): add commitizen check to CI

commitizen/cli.py, commitizen/commands/bump.py, commitizen/exceptions.py, docs/bump.md, tests/commands/test_bump_command.py
Closes #435 
`cz bump 1.2.3` uses 1.2.3 as new version
=> Bump: support manual version

commitizen/commands/check.py, tests/commands/test_check_command.py
=> feat: Ignore fixup! & squash!

.github/workflows/pythonpackage.yml, commitizen/bump.py, commitizen/commands/bump.py, commitizen/commands/check.py, scripts/format, scripts/test, tests/commands/test_bump_command.py, tests/commands/test_init_command.py, tests/conftest.py, tests/test_bump_create_commit_message.py, tests/test_bump_update_version_in_files.py, tests/test_cli.py, tests/test_git.py
Failing Windows Tests (_generated with_ `pytest-html` _plugin_):
[pytest_report.zip](https://github.com/commitizen-tools/commitizen/files/9844702/pytest_report.zip)
Fixes: Issue #602, #604
=> Specify `bash` shell in CI Workflows

commitizen/cli.py, commitizen/commands/bump.py, commitizen/defaults.py, docs/bump.md, tests/commands/test_bump_command.py, tests/test_conf.py, tests/utils.py
Closes #501 
Closes #573
I guess instead of the current implementation, I could have also changed the `bump_map` in the settings and not touched any of the remaining code? Please let me know which approach you’d prefer.
Still need to write tests and documentation.
As discussed in the connected issue.
Run the tests.
n/a
=> feat: add major-version-zero option to support initial package development

docs/README.md
Since Poetry 1.2.0 dependency groups are introduced, and `--dev` becomes deprecated, and instead `--with dev` has to be provided. This PR updates the documentation to reflect this change.
Change the documentation in order to reflect the updated way for dependency groups.
The documentation can be followed as it is, instead of getting warnings/ errors.
1. Review the documentation, and wether it reflects the desired state
=> docs(README.md): update poetry dev dependency usage

tests/commands/test_bump_command.py, tests/commands/test_init_command.py, tests/test_conf.py
as title
pass the test after installing the latest dependencies
1. `poetry update`
2. `poetry install`
3. `./scripts/test`
=> test: fix test case changes due to tomlkit upgrade

docs/config.md
Missing param in settings.
I've also moved the settings at the top. As this is something you may check often, while creating the file is done once at the beginning of the cz configuration.
=> docs(config.md): list settings first and add missing param

commitizen/commands/changelog.py, tests/commands/test_changelog_command.py
The current default setting for `tag_format` is `None`. This is not a problem for the `bump` command, since the `normalize_tag` function defaults to `$version` when no `tag_format` is passed. However it is a problem for the `changelog` command, which seems to explicitly demand a `tag_format` in order to run a rev-range lookup. This creates issues like https://github.com/commitizen-tools/commitizen/issues/622.
Either a sane default needs to be set for `tag_format` or the restriction in `changelog` has to be uplifted. In this commit the latter has been chosen. A test is also implemented to check that `changelog` will always compute a rev range with the default tag format.
Fixes https://github.com/commitizen-tools/commitizen/issues/622
See …
=> fix(changelog): allow rev range lookups without a tag format

.github/dependabot.yml, .github/workflows/pythonpackage.yml, .gitignore, commitizen/cli.py, docs/README.md, docs/tutorials/gitlab_ci.md, poetry.lock, pyproject.toml, tests/test_bump_find_version.py, tests/test_bump_update_version_in_files.py
**Proposal:** This PR sunsets Python 3.6 and adds supports Python 3.11 given Python 3.6 is been sunsetted 1 year ago and lately buils are not running anymore on Python 3.6 (see https://github.com/commitizen-tools/commitizen/pull/631/checks as example).
**BREAKING CHANGE:** Python 3.6 is not supported anymore 
New package don't advertise support for Python 3.6 anymore
CI stop running on Python 3.6
Python 3.11 support is now tested in CI
CI is green again
Fixes #607 
I permitted myself to submit this PR because builds are now failing on Python 3.6 for new PR like mine: #632
=> build(python): Sunset Python 3.6 and support Python 3.11

tests/conftest.py
This PR create a git sanbox to isolated from the host configuration.
As example, in my case given I have a default signin key, without this fix, pre-commit fail trying to prompt for gpg credentials.
This ensure that test are run on a default configuration with `user.name` and `user.email` already set and nothing else.
Custom git user configuration does not interefere with the test suite anymore
Run the tests with any change in you git config
Submitted on `v3` because of the working CI (and it is my current base for the next PRs) but the issue already exists on `master`
=> test(git): ensures that global git user settings are not interfering with the tests

commitizen/cz/__init__.py, docs/customization.md, poetry.lock, pyproject.toml, tests/test_bump_find_increment.py, tests/test_factory.py
This PR is proposal implementation for #495
It switches to an `importlib.metadata.EntryPoint`-based plugin loading instead of pattern matching on the module name.
Plugins are now loaded using the `commitizen.plugin` entrypoint while legacy plugins are not loaded anymore but a warning is raised for each legacy plugin seen.
BREAKING CHANGE: Plugins are now exposed as `commitizen.plugin` entrypoints
Internal plugins are exposed as `commitizen.plugin` entrypoint. and seen as plugins.
External plugins are seen too as soon as they are exposed as `commitizen.plugin` entrypoint.
Legacy plugins are not loaded and a warning is raised for each legacy plugin detected.
Try to use any internal plugin without changes in configuration: should work
Try a legacy plugin: KO
Try a plugin migrated to the …
=> feat(plugins): Switch to an importlib.metadata.EntryPoint-based plugin loading

commitizen/commands/check.py, commitizen/commands/init.py, commitizen/exceptions.py, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_check_command.py, tests/commands/test_commit_command.py, tests/commands/test_init_command.py, tests/commands/test_other_commands.py, tests/test_bump_create_commit_message.py, tests/test_cli.py, tests/test_git.py
This PR make `cz` report errors if user want to install pre-commit hook and failed, which fixs #428. 
Run `cz init` will print error if there is something wrong.
```
❯ cz init
? Please choose a supported config file: (default: pyproject.toml) pyproject.toml
? Please choose a cz (commit rule): (default: cz_conventional_commits) cz_conventional_commits
No Existing Tag. Set tag to v0.0.1
? Please enter the correct version format: (default: "$version")
? Do you want to install pre-commit hook? Yes
pre-commit is not installed in current environement.
Installation failed. See error outputs for more information.
```
And the exit code should not be 0.
```
❯ echo $?
24
```
```
cz init
test $? != 0
```
I found that `TestPreCommitCases` has some duplicated code. Should they be extracted to methods?
=> Report hook installation fail

commitizen/commands/check.py, tests/commands/test_check_command.py
When running `git commit --verbose` when using commitizen as a pre-commit we
have a bug because of the diff that is incorrectly included.
I have filtered out everything that is auto-generated by git and normally excluded.
When running a verbose git commit with `git commit --verbose` I expect to have the diff not included in the message (and this causes a bug that raise an not expected error to the user)
When using commitizen as a pre-commit check:
1. Run `git commit -v`
2. Write one line commit like `feat: i am a test feature`
3. No errors should happen
https://github.com/commitizen-tools/commitizen/issues/598
=> fix: update filter comments to exclude git diffs

tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_commit_command.py, tests/conftest.py, tests/test_bump_create_commit_message.py, tests/utils.py
This PR follows #638 and extend the isolation to any `GIT_` prefixed variables. It also ensure that every test requiring a `tmp_git_project` or `tmp_commitizen_project`  fixture has it, even for test expecting a failure (to ensure the proper failure).
This fixes some false negatives in `pre-commit` as well as ordering side-effects for tests that were missing the fixture like [this build](https://github.com/commitizen-tools/commitizen/actions/runs/3796117778/jobs/6455902375) failing on some totally unrelated (and untouched) cases.
There is few misc fixes and redundancy removal (lots of unnecessary nested `.as_cwd()` calls as well as some fixtures extracted into `@pytest.mark.usefixtures()` when not used in the test but still requiring the fixture setup))
=> test: improve git isolation and fixes test missing a repository

.github/workflows/bumpversion.yml, .github/workflows/docspublish.yaml, .github/workflows/homebrewpublish.yaml, .github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yaml, .pre-commit-config.yaml, commitizen/config/yaml_config.py, scripts/test, tests/test_conf.py
* feat(yaml_config): add explicit_start for yaml output
* ci(pre-commit): set linter and test stage to push stage
* ci(scripts): add -nr 3 to commitizen commit check
`cz init` generates `cz.yaml` that complys `yamllint` 
1. `cz init`
2. choose `.cz.yaml` or `cz.yaml`
3. install yamllint
4. `yamllint cz.yaml` or `yamllint .cz.yaml`
#618
=> Generate .cz.yaml that comply yamllint

.github/workflows/pythonpackage.yml, commitizen/cmd.py, commitizen/commands/bump.py, commitizen/defaults.py, commitizen/exceptions.py, commitizen/hooks.py, docs/bump.md, tests/commands/test_bump_command.py, tests/test_bump_hooks.py, tests/test_conf.py
To make commitizen integrate even better, new configuration keys hooks_pre_bump and hooks_post_bump were added to allow to run arbitrary commands prior to and right after running bump.
I've backported the work done by @janw and slightly adjusted it:
- updated the patch to apply against the latest version of commitizen
- run `hooks_pre_bump` hooks *after* the versions have been updated but *before* they are committed and tagged, so additional documentation can be generated with the new version or other generators can be run and staged.
- I couldn't think of a usecase why you would want to hook into the process of generating the changelog so I completely removed this part.
1. Add something like this in your commitizen config file:
```toml
[tool.commitizen]
hooks_pre_bump = [
"touch …
```
=> feat(bump): added support for running arbitrary hooks during bump

commitizen/commands/bump.py, commitizen/commands/version.py, commitizen/defaults.py, commitizen/exceptions.py, commitizen/providers.py, docs/config.md, docs/exit_codes.md, docs/faq.md, mkdocs.yml, poetry.lock, pyproject.toml, tests/commands/test_bump_command.py, tests/commands/test_version_command.py, tests/test_conf.py, tests/test_version_providers.py
This PR is a proposal because I know it has been stated than there won't be an official PEP621.
This PR doesn't focus on `PEP621` but on opening the version source of trust by introducing a version provider.
If has been splitted in multiple commits that can be removed from the PR depending on your acceptance.
The first one is simply introducing the entrypoint `commitizen.provider` and the `commitizen` provider which is the current scheme (version taken from commitizen configuration) and backward compatible.
The second one introduce some common TOML-based formats (PEP621, poetry, Cargo) as `tomlkit` is style preserving. Those implementations does not suffer from the regexp side-effect aka. changing any field matching the criteria (happen as soon as you have another version matching in the …
=> Feature: version providers

commitizen/hooks.py, tests/test_bump_hooks.py
During development of #644, merging the hook environment variables with existing OS variables broke. This commit fixes that. I think it got missing during an additional rebase of that MR, but it is fixed again.
=> fix(bump): fixed environment variables in bump hooks

pyproject.toml
Relax charset-normalizer dependency to support 3.0.x
`poetry update` will update charset-normalizer to an up-to-date version, currently 3.0.1
Closes #635
=> build(poetry): relax charset-normalizer dependency to allow 3.0.x

pyproject.toml
Similar to #589
Allow for installation of argcomplete 2.1.x in commitizen enabled projects
=> Relax specification for argcomplete dependency

commitizen/commands/changelog.py, tests/commands/test_changelog_command.py, tests/utils.py
This MR comes from an issue raised [here](https://github.com/commitizen-tools/commitizen/issues/660)
Topological ordering should be used when ordering commits in changelog history. This allows commits to be shown properly in the order they were added to the codebase, even if non-linear merges were used
- No documentation to update
With a git history that has non-linear merges, I want my commits to be ordered in the order that they were introduced in the codebase.
So having a git graph like so:
```bash
* feat: I will be merged first - (2023-03-01 11:35:51 +0100) |  (branchB)
| * feat: I will be merged second - (2023-03-01 11:35:22 +0100) |  (branchA)
|/
* feat: initial commit - (2023-03-01 11:34:54 +0100) |  (HEAD -> main)
```
If I merge `branchB` before `branchA` like so:
```bash
* …
```
=> fix(commands/changelog): use topological order for commit ordering

commitizen/defaults.py, pyproject.toml
Relaxes overly strict runtime dependency specifications for semver packages.
Allows for `commitizen` to be installed alongside current versions of runtime dependencies.
Closes #683
=> Relax runtime dependency specifications

tests/conftest.py
for old git like git-2.30 the tests broke my ~/.gitconfig file and created thousands of `name=GitHub` lines
I checked the git documentation and worked out a workaround for my situation. I think it should work for a fresh git too
```
ENVIRONMENT
GIT_CONFIG
Take the configuration from the given file instead of .git/config. Using the "--global" option forces this to ~/.gitconfig. Using the "--system" option forces this to
$(prefix)/etc/gitconfig.
GIT_CONFIG_NOSYSTEM
Whether to skip reading settings from the system-wide $(prefix)/etc/gitconfig file. See git(1) for details.
See also the section called “FILES”.
```
no touch my ~/.gitconfig
run tests 
```
➜  ~ cat /etc/issue
Debian GNU/Linux 11 \n \l
➜  ~ git --version
git version 2.30.2
```
=> test: fix git_sandbox for git<2.33

.github/dependabot.yml
commit message from dependabot now looks like
we want to make it `bump(poetry-dev): ...`
=> ci(dependabot): add prefix-development

commitizen/changelog.py, commitizen/commands/changelog.py, tests/commands/test_changelog_command.py, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_alpha_alpha_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_alpha_beta_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_alpha_rc_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_beta_alpha_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_beta_beta_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_beta_rc_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_rc_alpha_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_rc_beta_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_rc_rc_.md, tests/test_changelog.py
This changes lets the changelog be generated for version bumps from a prerelease version without new commits, which the `bump` command already allows.
User should be able to bump a prerelease version and generate a changelog for the new version without adding new commits
1. Generate a prerelease version with `bump` command: `cz bump --changelog --prerelease alpha`
2. Generate a new version with `bump` command without adding new commits: `cz bump --changelog [--prerelease beta]`
Fails when attempting to generate the changelog with `--changelog` flag
```shell
$ cz bump --changelog --prerelease alpha --yes
bump: release 0.37.0 → 0.38.0a0
Automatically generated by Commitizen.
tag to create: v0.38.0a0
increment detected: MINOR
[main 013cdd0] bump: release 0.37.0 → 0.38.0a0
4 files changed, 9 …
```
=> fix: bump changelog for prerelease without commits

commitizen/bump.py, commitizen/defaults.py, tests/commands/test_changelog_command.py, tests/commands/test_changelog_command/test_breaking_change_content_v1_with_exclamation_mark.md, tests/commands/test_changelog_command/test_breaking_change_content_v1_with_exclamation_mark_feat.md, tests/test_bump_find_increment.py
This tests should pass, relates to:
#673
=> test: add test for 'additional' types in conventional commits

commitizen/cli.py, commitizen/commands/commit.py, docs/commit.md, docs/tutorials/auto_prepare_commit_message.md, hooks/post-commit.py, hooks/prepare-commit-msg.py, hooks/prepare-commit-msg.sh, mkdocs.yml, tests/commands/test_commit_command.py
This pull request resolves #689 by implementing my proposal for it.
See https://github.com/commitizen-tools/commitizen/issues/689#issuecomment-1526221321.
New option:
1. Run `cz commit --write-message-to-file message.txt` in a Git repository with staged changes and complete interactive dialog
1. The content of `message.txt` should be the generated commit message
1. The other behavior of `cz commit` is unchanged
Git hook:
1. Follow the tutorial in `docs/tutorials/auto_prepare_commit_message.md` in a Git repository with staged changes
1. When running `git commit` or `git commit -m "..."`, the usual `cz commit` interactive dialog runs
1. After completing the dialog (and exiting the GIT_EDITOR if it opened), a new commit with the generate commit message is created
These changes supersede #249 …
=> feat(commit): add --write-message-to-file option

poetry.lock, pyproject.toml
=> fix: add support for importlib_metadata 6

commitizen/providers.py, tests/test_version_providers.py
This PR adds support for `Cargo.toml` workspaces.
When the root `Cargo.toml` of a project is:
```
[workspace.package]
version = "0.1.0"
```
In your apps you can have a `Cargo.toml` with:
```
[package]
version = { workspace = true }
```
=> feat: add support for cargo workspaces

commitizen/cli.py, commitizen/commands/bump.py, docs/bump.md, tests/commands/test_bump_command.py
Add an option to redirect git command output to stderr instead of stdout.
This is useful used in conjunction with `--changelog-to-stdout` if you don't need/want the resulting output to contain the `git commit` log messages.
When issuing `cz bump --changelog-to-stdout > file.md`, `file.md` will contain the git output of the `git commit` command (eg. something like `[<branche> <SHA>] bump: x.y.z -> a.b.c + diffstats`. When passing the `--git-output-to-stderr` option, this output is written to stderr instead of stdout allowing the resulting file to only contain changelog-related stuff.
1. `cz bump --changelog-to-stdout --git-output-to-stderr > body.md`
2. Ensure body.md does not contain git-related traces.
=> feat: Add option in bump command to redirect git output to stderr

commitizen/changelog.py, commitizen/commands/changelog.py, commitizen/git.py, poetry.lock, pyproject.toml, tests/commands/test_changelog_command.py, tests/utils.py
All tags used to generate the changelog must be version tags. 
This PR fixes two issues:
- The 'latest' commit was not being checked for it being a version tag, which can result in some non-version tag written as a header for the changelog
- The `rev-range` created when running `cz changelog 3.2.0` could use a non-version tag as a lower-bound, resulting in an incomplete changelog if the non-version tag was in the middle of two versions.
Changelogs should be generated only with version tags as headers. Tags are indeed being checked that they are version tags when generating the changelog [here](https://github.com/commitizen-tools/commitizen/blob/v3.2.1/commitizen/changelog.py#L58), but this logic is missing for the _latest_ commit's tag.
This means that changelogs can be generated with an …
=> fix: use only version tags in changelog

commitizen/bump.py, commitizen/version_schemes.py
This is a small PR updating a few lines of code where SemVer types (major/minor/patch) are referred to as literal strings instead of constants defined in `commitizen.defaults` module.
I guess the changes made do not require tests.
=> refactor: replace SemVer type literals by respective constants

commitizen/bump.py, commitizen/changelog.py, commitizen/changelog_parser.py, commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/commands/check.py, commitizen/commands/commit.py, commitizen/commands/init.py, commitizen/config/base_config.py, commitizen/config/json_config.py, commitizen/config/toml_config.py, commitizen/config/yaml_config.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/cz/customize/customize.py, commitizen/cz/jira/jira.py, commitizen/defaults.py, commitizen/out.py, docs/config.md, docs/tutorials/writing_commits.md, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_init_command.py, tests/test_bump_update_version_in_files.py, tests/test_bump_update_version_in_files/test_multiple_versions_to_bump_with_eol_.toml, tests/test_bump_update_version_in_files/test_multiple_versions_to_bump_without_eol_.toml, tests/test_changelog.py, tests/test_changelog_meta.py, tests/test_changelog_parser.py, tests/test_conf.py, tests/test_cz_customize.py
Adds unicode support by allowing configurable encodings to be specified (defaults to `utf-8`).
Fixes: Issue #516
=> Add Unicode Support

.github/labeler.yml, .pre-commit-config.yaml, docs/contributing.md, mkdocs.yml
* Fix auto-added label for newly created PR (should be `pr-status: wait-for-review`)
* add PR, issue life cycle to documentation
GitHub Actions add `pr-status: wait-for-review` label when PR created
1. create a PR after this PR is merged
2. go to the created PR to check whether label `pr-status: wait-for-review` is added
=> Fix auto added label for newly created PR and add PR, issue life cycle to documentation

docs/contributing.md
Modifing the wrong README.md path to the correct path in the `docs/contributing.md`
1. execute `mkdocs serve`
2. http://127.0.0.1:8000/contributing/
=> docs(docs): modify the wrong content in contributing md

commitizen/commands/bump.py
before:
```
2nd git.commit error: ""
```
after
```
2nd git.commit error: "On branch master
Your branch is ahead of 'origin/master' by 1 commit.
(use "git push" to publish your local commits)
nothing to commit, working tree clean
"
```
- [-] Add test cases to all the changes you introduce
- [-] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [-] Update the documentation for the changes
1. create a commit
2. `cz bump`
=> fix: empty error on bump failure

commitizen/commands/commit.py, commitizen/defaults.py, docs/commit.md, tests/commands/test_commit_command.py, tests/test_conf.py
Add new configuration option `always_signoff`. When is set to `true`, commits will be always signed off. The `-s` option does not have to specified to `cz commit`.
* When `always_signoff` configuration option is set to `true`, always sign off commits created with `cz commit`, even if `-s` option has not been specified.
1. Add `always_signoff` option to `true` in configuration file.
2. Create commit using `cz commit` (without `-s` option).
3. Verify the resulting commit message contains `Signed-off-by:`. 
#785
=> feat(defaults.py): add always_signoff config option for commits

commitizen/cli.py, commitizen/commands/commit.py, commitizen/git.py, tests/commands/test_commit_command.py
Adding `cz commit` arg to  automatically stage every tracked and un-staged file
command `cz commit -a` will automatically stage every tracked and un-staged file .
1. cz commit -a
#554
=> feat(commands): add cz commit arg to automatically stage every tracked and un-staged file

.github/workflows/pythonpackage.yml
Reverts commitizen-tools/commitizen#846
There appears to be [an issue with this](https://github.com/codecov/codecov-action/issues/1091) release, which is currently still in beta. Suggesting this commit is reverted, as it's causing all new pull requests, [including mine](https://github.com/commitizen-tools/commitizen/pull/848), to fail. Can update to `v4` once the release is stable.
=> Revert "ci(deps): bump codecov/codecov-action from 3 to 4"

commitizen/config/json_config.py, commitizen/config/toml_config.py, commitizen/config/yaml_config.py, tests/test_conf.py
If there is already a config file with wrong format in cwd, `cz` would failed to parse and the exception is unhandled. #729 have fixed that for json config, but yaml and toml are not.
Fixes #577 
`cz` should report there is an error when parsing config file.
Execute following commands:
```sh
mkdir /tmp/cz-init
cd /tmp/init
echo 'i am not toml' > .cz.toml
cz init
```
and you will see error message like this:
```
Failed to parse .cz.toml: Invalid key "invalid content" at line 1 col 15
```
or this:
```
Failed to parse .cz.yaml: mapping values are not allowed here
in "<byte string>", line 1, column 6:
i: am: not: yaml
^
```
=> fix(conf): handle parse error when init

docs/config.md
Trivial error in the docs, but it caught me out setting up config for a library earlier. The configuration docs currently say that `version` is required if `provider = "commitizen"`, however, the correct key for this config value is `version_provider` (although such providers live in the `commitizen.provider` namespace and I wouldn't be surprised if choosing this name was discussed during the implementation of this feature, but haven't checked).
Please advise if I have misunderstood the config. Have read the relevant source code and got my implementation working nicely, but keen to be corrected if I have missed some nuance.
=> docs: typo - version_provider vs provider

.github/workflows/pythonpackage.yml, docs/README.md, docs/tutorials/gitlab_ci.md, poetry.lock, pyproject.toml
Drops support for Python 3.7 and updates the necessary dependencies.
* Closes https://github.com/commitizen-tools/commitizen/issues/857
=> feat: Drop support for Python 3.7

docs/tutorials/dev_releases.md, mkdocs.yml
As requested in the comments for [#570](https://github.com/commitizen-tools/commitizen/issues/570#issuecomment-1527529968), added a tutorial for "developmental releases".
- [N/A] Add test cases to all the changes you introduce
Addition to the "Tutorials" menu in the documentation.
1. Run `poetry run mkdocs serve`.
2. Visit <http://127.0.0.1:8000/>
3. Click on _Tutorials_ in the left-hand menu.
4. Click on _Developmental releases_ in the drop-down menu.
I've added examples for CircleCI (as this was the service I originally referenced), GitHub (as this would seem relevant to the current environment) and a catch-all using Unix time (which I've used elsewhere).
=> docs: add developmental releases tutorial

commitizen/bump.py, commitizen/defaults.py, tests/test_bump_find_increment.py
This change adds support for version bumping for custom types with a scope. Previously, a commit with the following message didn't increment the version.
```
$ git commit --allow-empty -m 'chore(scope)!: major change'
[master 0567ca4] chore(scope)!: major change
$ python ./commitizen/cli.py bump --dry-run
bump: version 3.5.2 → 3.5.2
tag to create: v3.5.2
[NO_COMMITS_TO_BUMP]
The commits found are not eligible to be bumped
```
Also, there is a minor bugfix in the bump command, that resulted in a wrongly calculated increment. (It's separated into a commit)
Not sure if I have to update the documentation, because I'd say it's the expected behavior from the conventional commit specification.
See steps to reproduce.
1. Add a commit 
```
git commit --allow-empty -m 'chore(scope)!: major change' …
```
=> Fix cz bump with custom type, scope and exclamation mark

commitizen/bump.py, commitizen/changelog.py, commitizen/changelog_parser.py, commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/commands/check.py, commitizen/commands/commit.py, commitizen/config/json_config.py, commitizen/config/toml_config.py, commitizen/config/yaml_config.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/cz/customize/customize.py, commitizen/cz/jira/jira.py, commitizen/defaults.py, commitizen/version_schemes.py, pyproject.toml, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_init_command.py, tests/test_bump_update_version_in_files.py, tests/test_changelog.py, tests/test_changelog_parser.py, tests/test_conf.py
Enable [pyupgrade rules](https://docs.astral.sh/ruff/rules/#pyupgrade-up) in `ruff` to automatically update syntax according to supported Python version.
Then apply it on all the repository.
No changes
=> style(ruff): enable `pyupgrade` (`UP`) rules and fix them all

.github/workflows/pythonpackage.yml
=> ci: add py3.12 to tests (#887)

docs/contributing.md
Fix a Markdown link on the **Contributing** page [here](https://commitizen-tools.github.io/commitizen/contributing/#before-making-a-pull-request) (point 7).
n/a
n/a
n/a
=> docs: fix Markdown link on Contributing page

.github/workflows/bumpversion.yml
previously, we used `a.b.c` to create release instead of `va.b.c`. This PR fixed this issue and replace the outdated action with ncipollo/release-action@v1
Closes: #923
=> ci(github-actions): fix release step tag name and use ncipollo/release-action@v1

.github/workflows/label_pr.yml
some of our PR are not correctly labeled, which is due to missing "checkout" step
https://github.com/actions/labeler#using-configuration-path-input-together-with-the-actionscheckout-action
=> ci(github-actions): fix laber-pr by adding necessary checkout step

.github/labeler.yml, .github/workflows/bumpversion.yml, .github/workflows/docspublish.yml, .github/workflows/label_pr.yml
move the "generate sponsor" step to docpublish workflow (not sure whether it's the root cause 🤔)
the sponsorship list generated correctly
=> ci(github-actions): move the generate sponsor step to docpublish workflow

.github/workflows/bumpversion.yml
By default, `ncipollo/release-action@v1` fails if no release happens, but we do not always make a release each time we merge a branch, which creates a lot of false alerts.
`ncipollo/release-action@v1`  should not fail when release already exists.
=> ci(github-actions): skip release action if no version is bumped

docs/bump.md
=> fix(version_scheme): fixed typo sever -> semver

docs/tutorials/github_actions.md
Fixing a simple typo in the `github_actions.md` doc
-  [x]  Test the changes on the local machine manually
-  [x]  Update the documentation for the changes
=> docs(github_actions.md): fix typo crendetial -> credential

docs/third-party-commitizen.md
Adding my plugin [cz-conventional-gitmoji](https://github.com/ljnsn/cz-conventional-gitmoji) to the third party tools section in the docs.
~- [ ] Add test cases to all the changes you introduce~
~- [ ] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test~
~- [ ] Test the changes on the local machine manually~
=> fix: add cz-conventional-gitmoji to the third party docs

pyproject.toml
=> Declare support for Python 3.12 in PyPI classifiers

commitizen/commands/bump.py, commitizen/version_schemes.py, docs/bump.md, tests/commands/test_bump_command.py, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_beta_alpha_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_rc_alpha_.md, tests/commands/test_changelog_command/test_changelog_incremental_with_prerelease_version_to_prerelease_version_rc_beta_.md, tests/test_version_scheme_pep440.py, tests/test_version_scheme_semver.py
Properly bump version numbers between prereleases respecting the commit messages bump levels.
Bump command should bump the version number according to the commit messages since the last final version when bumping between prereleases.
start at version 0.1.0
1. git commit --allow-empty --message 'fix: a fix'
2. cz bump --prerelease alpha → bumps to `0.1.1a0`
3. git commit --allow-empty --message 'feat: a feature'
4. cz bump --prerelease alpha → bumps to `0.2.0a0` instead of `0.1.1a1`
#688
=> fix: properly bump versions between prereleases

commitizen/commands/bump.py, commitizen/git.py, commitizen/providers/scm_provider.py, commitizen/version_schemes.py, tests/providers/test_scm_provider.py, tests/test_git.py, tests/test_version_scheme_pep440.py, tests/test_version_scheme_semver.py
The scm provider currently uses _all_ of the tags in the repo to determine the current version, but it should instead only consider tags that are upstream from the current commit.   This means commitizen currently consider tags that are in the future or on other branches when determining the version.  This doesn't make sense.  The pep621 provider doesn't determine the current version from the _latest_ commit of `pyproject.toml` or from commits on other branches, it looks at the current state of the repo. 
The expected behavior is that the current version should be determined by the "highest" version tag reachable by the current commit.  In order to determine "highest" I had to add sortability to `VersionProtocol`, but luckily this is already implemented by `BaseVersion`.
=> Fix SCM provider to only search tags that are reachable by the current commit

commitizen/cli.py, commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/cz/utils.py, commitizen/version_schemes.py, docs/bump.md, tests/commands/test_bump_command.py, tests/test_bump_create_commit_message.py
A way to add build-metadata from the cli using parameters, including being able to change them at as you want without disturbing the other version-logic in commitizen.
Should add additional functionality without disturbing anything.
1. cz bump --build-metadata a.b.c
2. cz bump
3. cz bump --build-metadata alongmetadatastring
4. cz bump
Closes: https://github.com/commitizen-tools/commitizen/issues/945
=> feat(bump): functionality to add build-metadata to version string

commitizen/bump.py, commitizen/cli.py, commitizen/commands/bump.py, commitizen/version_schemes.py, docs/bump.md, tests/commands/test_bump_command.py, tests/test_version_scheme_pep440.py, tests/test_version_scheme_semver.py
PR https://github.com/commitizen-tools/commitizen/pull/799 just merged which adds some nuance to prerelease bumping by improving the default logic for when to bump major versions and prerelease suffixes.   While this is an improvement over the original logic, it's still very prescriptive and I think there's room for debate over whether this is a one-size-fits-all solution.  There are scenarios where more control is required.
This PR adds `bump --exact` to honor the increment when a prerelease suffix is present, which provides the user with more control rather utilizing the current approach with its various edge cases. 
I made this change in support of a gitflow-on-autopilot workflow ([demo here](https://gitlab.com/chadrik/semver-demo)) using the common set of 3 branches:  `develop`, …
=> Add --exact option to bump, to force it to honor the increment for prereleases

commitizen/changelog.py, commitizen/commands/changelog.py, commitizen/cz/base.py, docs/bump.md, docs/customization.md, tests/test_changelog.py
This PR allows `changelog_message_build_hook` to remove commits from the changelog just by returning `None` or any falsy value.
Testing this PR made me realize than the hook was ignored for body messages and fix this case.
Note: some changes are just formatting from the `scripts/format` execution.
The feature: if the `changelog_message_build_hook` return a falsy value (`None` or `{}` from expected types), the commit will be skipped into the changelog.
Side-effect fix: the hook is also executed on the parsed body message given it is generated using the same `commit_parser`
1. Create and use a custom plugin class
2. Override its `changelog_message_build_hook`
3. Check that commit for which it returned None are not included in the changelog
Next step will be to allow the opposite: allows …
=> feature: `changelog_message_build_hook` can remove message by returning a falsy value

commitizen/changelog.py, tests/test_changelog.py
This PR ensure that `changelog_message_builder_hook` has access to `change_type` and can modify it.
Also, change type remap is only tried if we actually have a parsed message (save a few dict iterations)
`changelog_message_builder_hook` can access the `change_type` field (which was removed before the hook was called) and modify it (it was stored and remapped before the hook can modify it).
1. write a custom `changelog_message_builder_hook`
2. make it read (it should be present) and optionally update the `change_type`
3. check that the rendered changelog has the updated change type
=> fix(changelog): ensure `changelog_message_builder_hook` can access and modify `change_type`

commitizen/changelog.py, commitizen/cz/base.py, docs/customization.md, tests/test_changelog.py
This PR allows to `changelog_message_builder_hook` to generate multiple changelog entries from a single commit (sequel to #1001).
This PR includes #1002 as it touches the same part (so first commit will automatically be removed as soon as #1002 is merged)
If you return an `Iterable` of parsed messages (aka. dicts) instead of a single one, you can add multiple changelog entries for the same commit.
1. Create a custom `changelog_message_build_hook`
2. Return an iterable of entries 
3. Generate changelog without failure
4. Check that all entries are in the changelog
Follow #1001 
Requires #1002 which is included
=> feat(changelog): `changelog_message_build_hook` can now generate multiple changelog entries from a single commit

commitizen/commands/changelog.py, tests/commands/test_changelog_command.py
Ensures that changelog hook is executed with `dry_run=True`
As a user, when I run the `changelog` or `bump` command with `dry_run=True`, I want my `changelog_hook` to be executed, so the preview includes changes from the hook.
1. Register a changelog hook which is modifying the result
2. run the `bump` or the `changelog` command
3. see the changelog changes in the resulting preview
=> fix(changelog): changelog hook was not called on dry run

commitizen/out.py
To be consistent with the build [`warnings`](https://docs.python.org/3/library/warnings.html) module behavior and to avoid breaking the changelog when using `--changelog-to-stdout`, all warnings generated with `commitizen.out.warn()` are printed to `stderr`
Whatever the warning raised during a `bump` or a `changelog` command, they should be printed to `stderr`.
More especially, when you are trying to run one of the above command with `--changelog-to-stdout` and your repository have some tags not matching the tag pattern, changelog should not be mixed with repeated `InvalidVersion GitTag('not-a-version', 'sha1', 'yyyy-mm-dd')` statements.
Add a git tag not matching the `tag_format` to your repository.
Run the `cz bump --changelog-to-stdout --git-output-to-stderr > CHANGELOG.md` command. …
=> fix(warnings): all warnings should go to `stdout`

commitizen/commands/changelog.py, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py
=> fix(changelog): include latest change when dry run and incremental

commitizen/changelog.py, commitizen/commands/changelog.py, commitizen/cz/base.py, docs/customization.md, tests/commands/test_changelog_command.py, tests/test_changelog.py
This PR adds an optional `changelog_release_hook` allowing to customize/enrich each changelog release the same way we can customize/enrich each commit
End user and plugin developers can add attributes to each release dict and use them in their changelog template
- add a `changelog_release_hook` to a plugin
- make it add some attributes to each release
- access/render them in the changelog template
=> feat(changelog): adds a `changelog_release_hook` called for each release in the changelog

commitizen/changelog.py, docs/customization.md, tests/test_changelog.py
…
This PR adds the `sha1`, `author` and `author_email` field to each commit/changelog change.
Fixes #987 
Template can access `sha1`, `author` and `author_email` on each changelog entry
Override the changelog template and try using `change.sha1`, `change.author` and `change.author_email`, it should be defined for each.
This change is easy but comes with a drawback which needs discussion before merge:
this is really increasing memory usage by commit. While it is impact-less on small repositories, it can make commitizen not fit in memory on big repositories (might need an estimation to measure impact).
So we need to discuss whether the overhead is acceptable or not and if this is OK should be merged as it is, opt-in and protected by a flag, a plugin only feature (consistent with the fact …
=> feat(changelog): expose commits `sha1`, `author` and `author_email` in changelog tree (fix #987)

commitizen/commands/init.py, tests/commands/test_init_command.py
When we run cz init in a project with existing tags, when it comes to the question ?` Please choose the latest tag:  (Use arrow keys)`. We list the tags in ascending order. However, the latest tag is most likely with the largest number. Thus list the tags in reverse order makes more sense.
Closes: #760 
in `Please choose the latest tag: `
when latest tags are ["0.0.1", "0.0.2"],
the choices should be ["0.0.2", "0.0.1"] 
run test cases in
tests/commands/test_init_commands.py
=> fix(command-init): "cz init" should list exisitng tag in reverse order

commitizen/git.py, tests/test_git.py
When the file path used in a commit contains spaces, the commit command should execute correctly. This fix addresses the issue where spaces in file names or paths previously caused errors with the git commit command.
1. Create a file with spaces in its name or path using touch "temp file".
2. Add the file to git with git add "temp file".
3. Execute the commit using cz c.
The test included here serves as a straightforward workaround, employing mocker for testing.
@Cliying94 is on the path to crafting a detailed integration test that begins with the commit operation.
Related: #572
=> Resolve tempfile path spaces issue in git commit function

commitizen/cz/conventional_commits/conventional_commits.py, commitizen/defaults.py, tests/test_changelog.py
commit_parser in [commitizen/defaults.py](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/defaults.py) is only for cz_conventional_commit rather than all commitizens. This PR is to move commit_parser from commitizen/defaults.py to [conventional_commits.py](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/cz/conventional_commits/conventional_commits.py)
commit_parser in commitizen/defaults.py is removed, and will be directly retrieved from ConventionalCommitsCz.
Related to #818
=> move cz_conventional_commit defaults out of project wide default

CHANGELOG.md
When commit the files in #1047, `cz` suggest to correct typos in `CHANGELOG.md`
N/A
N/A
N/A
=> docs(CHANGELOG): fix typo in the file

docs/images/cli_help/cz___help.svg, docs/images/cli_help/cz_bump___help.svg, docs/images/cli_help/cz_changelog___help.svg, docs/images/cli_help/cz_check___help.svg, docs/images/cli_help/cz_commit___help.svg, docs/images/cli_help/cz_example___help.svg, docs/images/cli_help/cz_info___help.svg, docs/images/cli_help/cz_init___help.svg, docs/images/cli_help/cz_ls___help.svg, docs/images/cli_help/cz_schema___help.svg, docs/images/cli_help/cz_version___help.svg, poetry.lock, pyproject.toml, scripts/gen_cli_help_screenshots.py
Add a script to generate screenshot of all cli help contents. 
Execute `scripts/gen_cli_help_screenshots.py` will generate screenshots of cli help instructions
1. Execute `scripts/gen_cli_help_screenshots.py`
2. Check each of content insides `commitizen.cli`'s `data` is match its screenshot in `docs/images/cli_help/` folder.
Considering the purpose of the file is more closed to a script, put it into scripts folder.
Should add test and update the documentation accordinately after the change is accepted.
=> cli(script): gen screenshot for cli helps

.github/workflows/docspublish.yml
The doc publish action is broken due to https://github.com/commitizen-tools/commitizen/pull/1057. The root cause is that the env var used has been changed since peaceiris/actions-gh-pages@3
=> ci(github-actions): update env var used in doc publish actions

commitizen/cli.py, commitizen/config/__init__.py, commitizen/exceptions.py, docs/README.md, tests/test_cli.py, tests/test_conf.py
CLI now have an option `--config` can specify the config file path,
if the config file is not in root folder, user can specify the located file as well. 
`cz` now have an option to specify config file,
if the given file is existed, will only read configuration from the given file,
else, a error would be raise since the given file do not exist.
Execute any `cz` command with `--config` option, if the config file do not exist, a error would raised.
resolve #656
=> feat(cli): add config option to specify config file path

.github/workflows/bumpversion.yml, .github/workflows/docspublish.yml, .github/workflows/homebrewpublish.yml, .github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml, scripts/test
Currently, local development checking (pre-commit) and CI checking are inconsistent. Changing the command run in GitHub Actions to pre-commit for consistent development experience.
GitHub Actions should check the same thing as pre-commit (local development)
Wait for CI to run
=> Run pre-commit in GitHub Actions

commitizen/bump.py, commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/git.py, docs/bump.md, tests/commands/test_bump_command.py, tests/test_bump_update_version_in_files.py, tests/test_bump_update_version_in_files/test_update_version_in_globbed_files.toml
This PR adds support for glob patterns in version files.
Bump changelog generation has been simplified a bit in the process.
`version_files` accept glob patterns instead of raw file names, and all the matching files should be properly bumped and added to the commit when bumping.
1. Defined one or many glob patterns in `version_files`, with an optional line regex
2. Bump a release
3. Check that all expected files have been updated with the new version, and committed (if using git)
Implements and fixes #1067
=> feat(bump): `version_files` now support glob patterns (fix #1067)

commitizen/version_schemes.py, docs/bump.md, docs/config.md, pyproject.toml, tests/test_version_scheme_semver2.py
This PR adds a `semver2` version scheme which is applying strict `prerelease` formatting as described in [SemVer 2 Item 9](https://semver.org/spec/v2.0.0.html#spec-item-9) and [Semver 2.0.0 Item 11](https://semver.org/spec/v2.0.0.html#spec-item-11), meaning:
- each prelease identifier should be separated by a dot
- dash is part of the identifier, not a separator
- precedence rules should be applied on identifiers
As a consequence, the `1.2.3-alpha0` form is not respecting those rules (`1.2.3-alpha10` has not proper precedence over `1.2.3-alpha2`), nor `1.2.3-alpha.0-dev.0` as its prerelease identifiers will be `alpha`, `0-dev`, `0` while it should be `alpha`, `0`, `dev` and `0`.
Note that Semver 2 is underspecified on this point (there is no formal description of what are the expected …
=> feat(schemes): adds support for SemVer 2.0 (dot in pre-releases) (fix #1025)

.github/workflows/generate_cli_screenshots.yml
After any pull requested merged, this Github Action Workflow will be triggered and will updated the CLI screenshots.
I tested manually using an clone of **commitizen** repo.
General view:
Generate CLI screenshots using the **scripts/gen_cli_help_screenshots.py**:
Push updated images to repository:
=> feat(ci/cd): automates the generation of CLI screenshots

.pre-commit-hooks.yaml, CHANGELOG.md
I saw that there were typo fixes in CHANGELOG.md in the past (e.g. 90e2fd84b918153facf7a41d6ff40e2c75839c53) so decided to do again.
Ran `codespell -w` while on top of 
- #1136 
so to have proper config available.
Note that when I did `pre-commit run codespell --all` I think it ignored  CHANGELOG.md 
```
❯ pre-commit run codespell --all
Run codespell to check for common misspellings in files.......................Failed
- hook id: codespell
- files were modified by this hook
FIXED: .pre-commit-hooks.yaml
pre-commit run codespell --all  5.87s user 0.62s system 969% cpu 0.669 total
```
=> docs: fix a few typos in CHANGELOG.md and .pre-commit-hooks.yaml

commitizen/changelog_formats/base.py
#1110
add encoding when open changlelog_file
=> fix(base.py): add encoding when open changlelog_file

commitizen/defaults.py, docs/commands/bump.md, docs/config.md, docs/faq.md, docs/getting_started.md, tests/test_conf.py
Add support to configure commitizen through `cz.toml` file.
Be able to initialize and configure commitizen through `cz.toml`
<details>
<summary>Test the new config file</summary>
<br/>
1. Rename the pyproject.toml to whatever
2. Run `cz init` and you will see the new possible config file
Successfully created the `cz.toml`:
</details>
<details>
<summary>About this feature be already covered by current tests</summary>
<br/>
Since its just an new filename, not extension nor format, its already fully covered by tests.
`tests/test_conf.py::TestReadCfg` already cover the tests on `.toml` extension:
And also pass all other tests:
</details>
Closes: #1111
=> feat(config_files): add suport for "cz.toml" config file

.pre-commit-config.yaml, pyproject.toml
So people could just run "codespell" without pre-commit and have centralized configuration for tools (the others are already in pyproject.toml)
- [N/A] Add test cases to all the changes you introduce
I did ;) 
```shell
❯ ./scripts/format
+ poetry run python -m ruff format commitizen tests
/home/yoh/venvs/dev3.11/bin/python: No module named ruff
❯ ./scripts/test
ImportError while loading conftest '/home/yoh/proj/misc/commitizen/tests/conftest.py'.
tests/conftest.py:10: in <module>
from pytest_mock import MockerFixture
E   ModuleNotFoundError: No module named 'pytest_mock'
```
=> style: move codespell configuration to pyproject.toml

.github/workflows/docspublish.yml
Job `update-cli-screenshots` was failling when no changes detected on `docs/images/cli_help` and blocking other jobs to run.
Closes: #1138
Job `update-cli-screenshots` must be skipped if no changes detected on `docs/images/cli_help`
I made two commits:
1. Commit with no changes related to CLI, so theres no changes detected from `update-cli-screenshots` (**114383c**).
2. Commit with changes on CLI (changed description of commands) (**b585baf**).
Note that commit with no changes exits with status 0 and don't creates the commit "docs(cli/screenshots): update CLI screenshots"
=> ci: skip 'update-cli-screenshots' if no changes

commitizen/changelog_formats/__init__.py, commitizen/cz/__init__.py, commitizen/providers/__init__.py, commitizen/version_schemes.py, poetry.lock, pyproject.toml, tests/test_factory.py, tests/test_version_schemes.py
[importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) as used by `commitizen` was first shipped with Python 3.10. The backport from [importlib_metadata](https://importlib-metadata.readthedocs.io/) is only required for Python <3.10.
`commitizen` no longer has a direct "runtime" dependency on the `importlib_metadata` backport for Python >=3.10, while using the backport for Python <3.10.
=> build(deps): remove `importlib_metadata` for Python >=3.10

commitizen/cli.py, commitizen/commands/bump.py, commitizen/exceptions.py, docs/commands/bump.md, tests/commands/test_bump_command.py, tests/commands/test_bump_command/test_bump_command_shows_description_when_use_help_option.txt
Adds a --get-next flag which determines the next version and writes it to stdout.
The new `--get-next` flag can be used to determine the next version based on the available commits, and output it to stdout. This can be useful in CI, for example to determine the version for a preview build image.
When provided, the `--get-next` flag makes commitizen behave similarly to `--dry-run`, it doesn't change any files and it doesn't create a tag. It determines the next version the same way a dry run does. It writes the next version to stdout, with no other output. 
The flag can't be used with `--changelog`, `--changelog-to-stdout` and `MANUAL_VERSION`, a `NotAllowed` exception will be raised if these options are provided together with `--get-next`.
An example use case is assigning the output to a …
=> feat(bump): add functionality to write the next version to stdout

.github/workflows/pythonpackage.yml, tests/commands/test_bump_command.py, tests/commands/test_bump_command/test_bump_command_shows_description_when_use_help_option.txt, tests/commands/test_changelog_command.py, tests/commands/test_changelog_command/test_changelog_command_shows_description_when_use_help_option.txt, tests/commands/test_check_command.py, tests/commands/test_check_command/test_check_command_shows_description_when_use_help_option.txt, tests/commands/test_commit_command.py, tests/commands/test_commit_command/test_commit_command_shows_description_when_use_help_option.txt, tests/test_bump_create_commit_message.py, tests/utils.py
GitHub Actions will run tests for Python 3.13 (dev).
closes #1145
=> ci(github-actions): add "3.13-dev" to Python tests (#1145)

docs/README.md, docs/tutorials/gitlab_ci.md
**docs(readme): document 'pipx' alternative installation steps**
Closes: #1113
-
-
-
=> docs(readme): document 'pipx' alternative installation steps

tests/commands/test_check_command/test_check_command_shows_description_when_use_help_option.txt
=> test(check): Python 3.13 help text format has been changed. Change the test accordingly

commitizen/changelog.py, commitizen/changelog_formats/asciidoc.py, commitizen/changelog_formats/base.py, commitizen/changelog_formats/markdown.py, commitizen/changelog_formats/restructuredtext.py, commitizen/changelog_formats/textile.py, commitizen/commands/changelog.py, commitizen/defaults.py, commitizen/providers/scm_provider.py, docs/commands/bump.md, docs/tutorials/monorepo_guidance.md, tests/commands/test_changelog_command.py, tests/test_changelog_format_asciidoc.py, tests/test_changelog_format_markdown.py, tests/test_changelog_format_restructuredtext.py, tests/test_changelog_format_textile.py
When the tag_format does not follow the allowed schemas patterns then changlog generation fails.
I am working in a mono repo with multiple `.cz.toml` configs (one per component) using `tag_format` to create tags for each component so they can be released independent of each other. When trying to generate the changelog for each component errors are generated see #845.
I was unsure how to add a test case for this if you have ideas please let me know and I will be happy to add.
changelogs will now be generated correctly when running `cz bump --changelog`
=> fix(changelog): handle custom tag_format in changelog generation

docs/tutorials/monorepo_guidance.md, mkdocs.yml
=> docs: improve monorepo docs

docs/README.md
Adding badge and instructions for `conda-forge` to `README` since #526 has been addressed.
Closes: https://github.com/commitizen-tools/commitizen/issues/526
=> docs: update README to include conda

docs/commands/check.md
The descriptions of the default values for allowed_prefixes are different on the [Commands check](https://commitizen-tools.github.io/commitizen/commands/check/#allowed-prefixes) and [Configuration](https://commitizen-tools.github.io/commitizen/config/#allowed_prefixes) pages.
The capitalization of "Pull request" is inconsistent; in practice, "request" must be lowercase to allow skipping the check.
=> docs: `Allowed Prefixes` default value typo

docs/third-party-commitizen.md
Add a new third party commitizen: a Deno provider. 
- [-] Add test cases to all the changes you introduce
- [-] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [-] Test the changes on the local machine manually
Related to #1257
=> docs(third-party-commitizen): add commitizen-deno-provider

docs/customization.md
I suggest to mention the multline support for input question in the documentation since it is already supported and a multiline description in the body is essential for good commits
Question `type = input` and option `multiline = True`, multiline input is possible
- created `.cz.yaml` and added the option `multiline: true` to the question `type: text` and  `type: input`
- in https://github.com/commitizen-tools/commitizen/issues/264#issuecomment-1620234279 [marcosdotme](https://github.com/marcosdotme) tested it in toml and reported it works 
Closes: https://github.com/commitizen-tools/commitizen/issues/264
=> docs(commit): add multiline option `questions` content table

commitizen/cli.py, commitizen/commands/commit.py, commitizen/git.py, docs/contributing.md, docs/images/cli_help/cz_commit___help.svg, tests/commands/test_commit_command.py, tests/commands/test_commit_command/test_commit_command_shows_description_when_use_help_option.txt, tests/test_git.py
Add one argument `-e/--edit` to commit command, to allow user to continue editing after filling up all the questions.
(Kudos to @MrMino! The `pytest-edit` project inspired me to come up with this idea.)
if `-e/--edit` enabled, the terminal would pop up editor with commit message after finishing the answering.
1. check out to this branch
2. make a commit with `cz c -e`
=> feat(commands/commit): add manual-edit functionality after answering questions

.pre-commit-hooks.yaml, poetry.lock
**fix(pre-commit-hooks)!: move 'check' to 'args' for global options**
Details: 'args: [...]' is not able to access '-nr NO_RAISE' global
arguments for example from a arguments configuration
**fix(pre-commit-hooks)!: allow empty ranges in 'commitizen-branch'**
Details: Pushing the same history from 'develop' to 'staging' for
example fails because range 'origin/HEAD..HEAD' is empty
> No commit found with range: 'origin/HEAD..HEAD'
Error `No commit found with range: 'origin/HEAD..HEAD'` not raised
Push same history to develop then staging
=> fix(pre-commit-hooks)!: allow empty ranges in 'commitizen-branch'

.pre-commit-config.yaml
When running `pre-commit run --all-files`, the following error was encountered.
```
[WARNING] hook id `commitizen-branch` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] hook id `linter and test` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] top-level `default_stages` uses deprecated stage names (commit, push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
This commit only only migrates the pre-commit config to the latest version.
Run `pre-commit run --all-files` without encountering warning
Run `pre-commit run --all-files`
=> build(pre-commit): migrate pre-commit conifg

.github/workflows/pythonpackage.yml
=> ci(github-actions): use 3.13 instead of 3.13-dev as Python 3.13 has already been released

commitizen/cli.py, commitizen/commands/commit.py, docs/getting_started.md, tests/commands/test_commit_command.py, tests/commands/test_commit_command/test_commit_command_shows_description_when_use_help_option.txt, tests/conftest.py
The `always_signoff` configuration or the CLI `-s` argument fail upon `git commit` call
due to the passed syntax being `git commit -- -s` rather than `git commit -s`.
The `--` is needed only on the commitizen CLI, and if no git argument is passed, the `--` should not be forced.
> signoff mechanic is deprecated, please use `cz commit -- -s` instead.
> fatal: /tmp/...: '/tmp/... is outside repository at '...'
* Warning and successful if `-s`
* Warning and successful if `-s --`
* No warning and successful if `-- -s`
* No warning and successful if `-- -s`
* No warning and successful with `always_signoff: true`
* No warning and successful if `--` with `always_signoff: true`
* No warning and successful if `-s` with `always_signoff: true`
* No warning and successful if `-s --` with …
=> fix(commit): resolve 'always_signoff' configuration and '-s' CLI issues

commitizen/commands/commit.py, tests/commands/test_commit_command.py
**feat(commit): add '--allow-empty' flag to commit command**
- Reworked over #1206 (commits follow-up)
- Reimplementation of #592, authorship preserved
Allow to invoke cz and create a commit without any change in it
```bash
git cz c --allow-empty
```
-
=> feat(commit): add '--allow-empty' flag to commit command

commitizen/commands/bump.py, tests/commands/test_bump_command.py
With the configuration options `update_changelog_on_bump` set to `True`, the command `cz bump --get-next` crashed, due to the mutual exclusive options `--get-next` and `--changelog`/`--changelog-to-stdout`. 
Changing this behavior to still throw a conflict when using both CLI options, but let `--get-next` take the precedence over `update_changelog_on_bump` configuration.
Now the configuration options `update_changelog_on_bump` can be set to whatever you want when using the `cz bump --get-next` command.
1. Build a commitizen config with `update_changelog_on_bump` flag set to true.
2. Add some commits to the target test project.
3. Run `cz bump --get-next`
4. The command should work and not throw an error.
=> fix(get-next-bump): fix to permit usage of --get-next option even when update_changelog_on_bump is set to true

docs/customization.md
Fixes documentation typos.
n/A
n/A
n/A
=> fixes yaml example

commitizen/cli.py, commitizen/commands/bump.py, docs/commands/bump.md, docs/images/cli_help/cz___help.svg, docs/images/cli_help/cz_bump___help.svg, docs/images/cli_help/cz_changelog___help.svg, docs/images/cli_help/cz_check___help.svg, docs/images/cli_help/cz_commit___help.svg, tests/commands/test_bump_command.py, tests/commands/test_bump_command/test_bump_command_shows_description_when_use_help_option.txt
superceed #696 
First draft of a new feature. The idea is to grant the user the capability to run `cz bump` without prior commits. The reasons are described in the associated issue. 
here we add an `--empty` parameter to the bump method
when this parameter is set and if no increment is find, a automatic "PATCH" is released. 
I'll wait for your feedback before working on tests and documentation.
Fix #662
=> feat: add --allow-no-commit option

docs/tutorials/auto_prepare_commit_message.md, hooks/post-commit.py, hooks/prepare-commit-msg.py
* docs(hooks): fix missing link
* style(hooks): improve type annotation
Everything should still be the same
None
=> Improve hooks type annotation and fix missing link

docs/tutorials/auto_check.md
Add "stages" explicitly to the hook example
As mentioned here: https://github.com/commitizen-tools/commitizen/issues/177#issuecomment-621939385, without the stages explicitly set, the hook always fails.
The hook should work when the message is correct on commit stage.
1. Add the hook as it is today.
2. Write a correct commit such as chore or feat
3. See the hook failing
=> Add "stages" explicitly to the hook example

pyproject.toml
In https://github.com/commitizen-tools/commitizen/pull/1354, commit check was missed. This PR is to add it back
invalid commit should raise an error when running `poetry commit-check`
1. randomly create a commit that does not follow conventional commit
2. `poetry commit-check`
=> ci(github-actions): add check-commit task

commitizen/commands/bump.py, docs/commands/bump.md, tests/commands/test_bump_command.py
If a prerelease offset is configured (I introduced this about 2 years ago with PR #614), no bump is possible with the manual version.
To do this, the configuration must first be changed and then reset after the bump.
For this reason, it makes more sense to remove the check that prevents the manual bump.
- I'm not sure where best to cover this case. Please give me a hint in which existing test file I could extend this.
Bumping a manual version works without changing the configuration file.
1. Use the follwoing Configuration
```toml
[tool.commitizen]
changelog_incremental = true
tag_format = "v$version"
update_changelog_on_bump = true
version = "1.2.0b13"
prerelease_offset = 1
```
2. `cz  bump 9.8.7`
=> fix(bump): manual version bump if prerelease offset is configured

.pre-commit-config.yaml, commitizen/providers/__init__.py, commitizen/providers/uv_provider.py, pyproject.toml, tests/providers/test_uv_provider.py, tests/providers/test_uv_provider/test_uv_provider.lock, tests/providers/test_uv_provider/test_uv_provider.toml
closes: #1349
as title
uv.lock should also updated when running `cz bump`
```shell
uv init
uv add commitizen
cz init
git add .
cz c
cz bump
```
=> feat(providers): add uv_provider

commitizen/tags.py
=> fix(tags): fixes ImportError on Python >=3.11 (#1363)

docs/getting_started.md
Change pre-commit example to `pre-push`, since that hook was renamed.
=> Update pre-commit example

commitizen/commands/init.py
=> fix(commands/init): add missing uv provider to "cz init"

commitizen/tags.py
and the regex used for validation
Starting in 4.4.0 due to #1297 when an invalid tag is present an exception is thrown. I would expect the tag is ignored.
This PR only improves the message, not the root cause
Before
```
packaging.version.InvalidVersion: Invalid version tag
```
After
```
packaging.version.InvalidVersion: Invalid version tag: '2.2.44.aa00000' does not match any configured tag format: re.compile('v?(?P<version>([0-9]+)\\.([0-9]+)(?:\\.([0-9]+))?(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z.]+)?(\\w+)?)')
```
1. create a non semver tag, ie. 2.2.44.aa00000
2. run `cz bump --dry-run`
=> fix: display invalid tag information

commitizen/changelog.py, commitizen/git.py, docs/customization.md, tests/test_changelog.py, tests/test_git.py
Expose commit parent(s) digests to the changelog process. This has an application
for projects that want to generate changelogs based on merge commits only, but it
is likely useful in more contexts, for example listing commits that belong to the same
PR under its own section.
The changelog generation code exposes the `parents` field with a list of parent
digests in git commits.
You can create a changelog template iterating the `parents` field of changes and
for merge commits you should have at least 2 parents.
Useful in the git workflow I'm currently working on, where merge commits cannot
be told apart by the changelog generation machinery and I need to distinguish them
as they are the only ones that can be taken into account without rewriting the project's
git history due to using varied …
=> feat(changelog): expose commit parents

.github/workflows/pythonpackage.yml
Fix CI by bumping deprecated `ubuntu-20.04` platform to `ubuntu-22.04`
=> ci(github-actions): bump deprecated ubuntu-20.04 to ubuntu-22.04

poetry.lock, pyproject.toml
Bump `argcomplete` dependency. There are [no breaking changes](https://kislyuk.github.io/argcomplete/changelog.html).
=> build(deps): bump argcomplete from 3.5.3 to 3.6.2

commitizen/commands/commit.py, tests/commands/test_commit_command.py
NamedTemporaryFile doesn't have a unlink function when delete=False is used
Fix https://github.com/commitizen-tools/commitizen/issues/1352
Fix the traceback, when `cz c --edit` is used
Save the commit message without an exception traceback.
1. Run cz commit -e
```
❯ cz c --edit
? Select the type of change you are committing fix: A bug fix. Correlates with PATCH in SemVer
? What is the scope of this change? (class or file name): (press [enter] to skip)
test
? Write a short and imperative summary of the code changes: (lower case and no period)
test
? Provide additional contextual information about the code changes: (press [enter] to skip)
test
? Is this a BREAKING CHANGE? Correlates with MAJOR in SemVer No
? Footer. Information about Breaking Changes and reference issues that this commit …
```
=> fix(commit): use os.unlink to remove temp file

docs/customization.md
The docs currently is missing a space, which makes the reference part of the table, and one of the url reference is broken.
The table and the reference are separate and the urls link to the right pages.
=> fix(docs): fix url link and table formatting in the customization docs

docs/tutorials/monorepo_guidance.md
The regex in the monorepo example seems to follow the Python formatting, but the toml text should follow the raw string instead (unless this library internally calls eval?).
Also the example does not follow regex format in the setting.
Update the regex pattern and update the example regex.
=> fix(docs): fix the regex and examples in the monorepo documentation

docs/tutorials/monorepo_guidance.md
Sorry I messed up, I forgot that you're required to escape the `\` in TOML. See #1398. I should have not removed it. Though the example should still be fixed so I'm only reverting the escapes. I'm really sorry D:.
TOML requires `\` to be escaped as `\\`
=> docs: Revert removal of escape in monorepo toml example

docs/customization.md, tests/test_cz_search_filter.py
Added search filter functionality to commit type selection in Conventional Commits. This allows users to quickly find commit types by typing part of the type name or description, enhancing user experience especially when working with many commit types.
Changes Made
1. Added use_search_filter: True to enable search filtering in the commit type selection.
2. Set use_jk_keys: False to prevent conflicts with search functionality (as j/k keys can be part of the search term).
3. Because the interaction questionary can not test directly so I test to verify search filter functionality and parameter works correctly.
4. Added newline at the end of file to comply with PEP 8 standards.
When a user types characters during commit type selection, the list of options is filtered to show only those …
=> feat: filter search for commit change type

commitizen/commands/changelog.py, tests/test_changelog.py
This pull request fixes the construction of the changelog file name in [changelog.py](cci:7://file:///home/yusin0903/commitizen/commitizen/commands/changelog.py:0:0-0:0) to ensure type safety and correct path handling. It also adds proper error handling for missing or invalid changelog file names.
The changelog command should now correctly resolve the changelog file path, regardless of whether the config path is set, and should raise a clear error if the file name is missing or invalid.
1. Run `poetry all` and ensure all checks pass.
2. Run the changelog command with and without the `--file-name` argument.
3. Verify that the changelog file is created at the expected location.
4. Check that an error is raised if the changelog file name is missing or invalid.
Sorry, I don' t know why my …
=> fix: cz bump subdir

commitizen/providers/cargo_provider.py, docs/config.md, tests/providers/test_cargo_provider.py
As depicted in #1201:
> In Rust, when you change the version of the app, the `Cargo.lock` file must be changed too.
This PR introduces the capability of updating the package version in the `Cargo.lock` file, where the package name is the one defined in `Cargo.toml`, for the `cargo` version provider. 
For [`cargo` version provider](https://commitizen-tools.github.io/commitizen/config/#version-providers), if a `Cargo.lock` file also exists within the same directory as `Cargo.toml`, the `Cargo.lock`'s `package.version` field whose `package.name` field is the same as `Cargo.toml`'s `package.name` field should be updated along with `Cargo.toml`.
Resolves: #1201
=> feat: add support for `Cargo.lock` version update

commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/commands/check.py, commitizen/commands/commit.py, commitizen/commands/example.py, commitizen/commands/info.py, commitizen/commands/init.py, commitizen/commands/schema.py, commitizen/factory.py, commitizen/version_schemes.py, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/commands/test_check_command.py, tests/commands/test_init_command.py, tests/conftest.py, tests/test_bump_update_version_in_files.py, tests/test_changelog_format_asciidoc.py, tests/test_changelog_format_markdown.py, tests/test_changelog_format_restructuredtext.py, tests/test_changelog_format_textile.py, tests/test_cz_customize.py, tests/test_factory.py, tests/test_version_scheme_pep440.py, tests/test_version_scheme_semver.py
=> refactor: fix typos

.github/pull_request_template.md
Make the checklist better.
NA
NA
NA
=> docs(pull_request_template): make the checklist holistic

commitizen/tags.py, tests/commands/test_bump_command.py, tests/commands/test_changelog_command.py, tests/test_changelog.py
Fix a regression introduced in the 4.4.0 by #1297: `bump` command is failing when an invalid tag is present and not listed in `ignored_tags` while it was just warning about before.
This PR restores this behavior (bump will work if an invalid tag is present, but a warning will be emitted).
The error/warning message is now the same whatever the place it is triggered.
Cf. #1410
Cf. #1410
Supersedes and closes #1410
=> fix(bump): don't fail if an invalid version tag is present (fix #1410)

commitizen/bump.py, commitizen/commands/changelog.py, commitizen/commands/init.py, commitizen/config/__init__.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/cz/customize/customize.py, commitizen/defaults.py, tests/test_conf.py
=> refactor(default): capitalize all constants and remove unnecessary variables

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml
The `labels` field didn't work as expected.
After this change, the issues created should be labeled correctly.
=> docs(ISSUE_TEMPLATE): correct labels

.github/workflows/label_issues.yml
I think the issue labels can be added automatically.
=> docs(label_issues): add logics for adding os related labels

commitizen/cli.py, tests/commands/test_changelog_command/test_changelog_command_shows_description_when_use_help_option.txt
This PR adds missing "--tag-format" argument to `cz changelog` command, similar to `cz bump` command.
The changelog command implementation already checks "tag_format" argument but cli support was just missing.
Tag format can be given as argument to `cz changelog` command. The changelog command already checks "tag_format" argument: https://github.com/commitizen-tools/commitizen/blob/be02801f92cb948ba86d8c1a9a306be4172e4efe/commitizen/commands/changelog.py#L85
=> feat(cli): add --tag-format argument to changelog command

commitizen/cz/customize/customize.py
Make the code shorter but still easy to read.
NA, this is refactor.
NA
=> refactor(customize): improve code readability

commitizen/bump.py, commitizen/changelog.py, commitizen/cli.py, commitizen/cz/utils.py, commitizen/defaults.py, commitizen/tags.py, tests/test_changelog.py
=> refactor: improve readability and fix typos

commitizen/commands/commit.py, tests/commands/test_commit_command.py
=> refactor(commit): simplify call

commitizen/git.py, tests/test_git.py
- ~~Removed `EOLTypes`. I think it's unnecessary.~~ Added it back but reorganized related code.
- It's probably not a good practice to name a variable `map`.
- Improve clarity of type hints.
- Extract some subroutines to improve readability.
=> refactor(git): code cleanup and test coverage

.github/workflows/label_pr.yml
Not sure if this works as expected, just trying.
The algorithm is not very strict, but I think it's still better than labeling manually by the maintainers.
---
To add or update labels according to a **Pull Request (PR) title**, you will need a custom step in your GitHub Actions workflow, because [`[actions/labeler](https://github.com/actions/labeler)`](https://github.com/actions/labeler) works based on the files changed in the PR, not the PR title.
Here’s how you can update your YAML to include PR title-based labeling using a `run:` script step:
```yaml
name: "Label Pull Request"
on:
pull_request_target:
jobs:
label-pr:
permissions:
contents: read
pull-requests: write
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
with:
sparse-checkout: |
.github/labeler.yml …
```
=> docs(label_pr.yml): add labels based on new PR title

commitizen/defaults.py, tests/test_defaults.py
relates: #1446
Related commit: https://github.com/commitizen-tools/commitizen/commit/94c02b3faf89cacf7186ad8a84e9200ede851574#diff-c951de16d627d82e01eb3ce8d7c4f0b28973ffe147520620762e7140ede2dd80
=> fix(defaults): add non-capitalized default constants back and deprecated warning

commitizen/cz/conventional_commits/conventional_commits.py, commitizen/cz/jira/jira.py
=> refactor: misc cleanup

commitizen/cli.py, tests/test_cli.py
=> refactor(cli): early return and improve test coverage

docs/commands/commit.md
=> docs(commit): rewrite command commit page

commitizen/cli.py
Resolves #1477 
- #1477 
I hope this can be merged into the `refactors` branch instead of `master`.
>
> ```text
> ```
=> Add type hints for cli.py

commitizen/commands/bump.py, commitizen/defaults.py, commitizen/version_schemes.py, docs/commands/commit.md, tests/test_defaults.py
=> fix(deprecated): mark deprecated will be removed in v5

poetry.lock
Now decli is typed in 0.6.3. That may make it easier for development.
https://github.com/woile/decli/pull/165
=> build(poetry): run poetry update to keep the packages up to date

docs/contributing_tldr.md, mkdocs.yml
I believe the new page makes it easier for developers to understand how to contribute effectively.
>
> ```text
> ```
=> docs(contributing): add Contributing TL;DR page

commitizen/commands/__init__.py, commitizen/commands/bump.py, commitizen/cz/conventional_commits/conventional_commits.py, commitizen/cz/jira/jira.py, commitizen/providers/__init__.py, commitizen/version_schemes.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_bump_find_increment.py, tests/test_cz_conventional_commits.py
resolved #1474 
- #1474
In addition to upgrading the version, two new rules have been added:
One is [RUF022](https://docs.astral.sh/ruff/rules/unsorted-dunder-all/), which is similar to `isort`. It checks for `__all__` definitions that are not ordered according to an "isort-style" sort.
The other is [RUFF100](https://docs.astral.sh/ruff/rules/unused-noqa/), which is similar to `unused-ignore` of `mypy`. It ensures that ineffective `# noqa` comments are removed.
Both of these can be automatically and safely fixed using `ruff check --fix`.
>
> ```text
> INFO    -  Doc file 'config.md' contains a link 'commands/bump.md#-post_bump_hooks', but the doc 'commands/bump.md' does …
```
=> Upgrade ruff and add RUF022 & RUF100

commitizen/commands/bump.py
=> refactor(bump): eliminate similar patterns in code

commitizen/git.py
=> refactor(git): simplify tag logic

commitizen/commands/bump.py, commitizen/commands/check.py, commitizen/git.py
Wait for #1466 
>
> ```text
> ```
=> refactor(git): retype get_commits parameter to make it more friendly to call sites

commitizen/commands/bump.py
Wait for #1466
>
> ```text
> ```
=> refactor(bump): simplify nested if

commitizen/cz/conventional_commits/conventional_commits.py
Run `cz check --message "blahblahblah"` multiple times to check if it's working as expected. We don't use capture groups of `re.compile(self.schema_pattern)` so it's fine to adjust the parentheses.
=> refactor(conventional_commits): make schema_pattern more readable

pyproject.toml
Closes #1493 
- Check whether the commit messages of a PR follows Conventional Commits pattern in CI.
- Move `check-commit` task before `cover` in `poetry all` command.
#1495 CI should not pass.
=> ci(pyproject.toml): strict check for invalid commit messages

commitizen/__init__.py, commitizen/commands/bump.py, commitizen/commands/changelog.py, commitizen/config/base_config.py, commitizen/config/toml_config.py, commitizen/cz/customize/__init__.py, commitizen/cz/customize/customize.py, commitizen/providers/base_provider.py, commitizen/providers/cargo_provider.py, commitizen/providers/commitizen_provider.py, commitizen/providers/poetry_provider.py, commitizen/version_schemes.py, poetry.lock, pyproject.toml, tests/commands/test_bump_command.py
=> build: add PGH003 and PGH004, add types-colorama

commitizen/defaults.py
=> docs(defaults): deprecate type Questions

commitizen/commands/changelog.py
=> fix(Changelog): fix _export_template variable type

commitizen/commands/bump.py, commitizen/commands/version.py, commitizen/providers/commitizen_provider.py
=> fix(CommitizenProvider): raise if version is None

.pre-commit-config.yaml, .taplo.toml
I noticed that I accidentally introduced unexpected style change in `pyproject.toml` (50fd65f), so I think it would be better if we have a consistent `toml` formatter.
Pre-commit hook now has `taplo` and it should work even without installing `taplo` locally.
1. Randomly insert white spaces in `pyproject.toml` and save without formatting to make the formatting bad.
2. `git commit`
3. The broken format should be fixed.
https://taplo.tamasfe.dev/configuration/formatter-options.html
=> docs(taplo): add toml formatter

commitizen/commands/changelog.py
=> refactor(Changelog): remove unnecessary intermediate variables for better readability

commitizen/changelog.py
=> refactor(changelog): shorten condition expression and early return

docs/commands/bump.md, docs/config.md
It was added in https://github.com/commitizen-tools/commitizen/pull/1070
but never documented AFAICT.
>
> ```text
> ```
=> docs(config.md): Document glob pattern support in `version_files`

docs/third-party-commitizen.md
I created a new Commitizen plugin called [cz-path](https://pypi.org/project/cz-path/) to make path prefix commit message style easier. Example: `ui/clock: fix dial` when staged files are all in `src/ui/clock` (`src` is by default removed).
=> docs(docs/third-party-commitizen.md): Add cz-path info

.github/workflows/docspublish.yml
=> ci(github-actions): fix sponsorship page generation

commitizen/commands/init.py, tests/commands/test_init_command.py
Before this change, the type of `tag_format` is `Any | Unbounded | str` at the end of the function. Actually `tag_format` is defined for all code paths.
- If `is_correct_format` is `True`, then `tag_format` is assigned `"v$version"`  and the function returns it.
- If `is_correct_format` is `False`, then `tag_format` is initialized in the if-block.
The function logic should be easier to understand after this change.
=> refactor(Init): fix unbounded variable in _ask_tag_format

commitizen/cli.py, commitizen/exceptions.py, tests/test_exceptions.py
- Now we validate if the error code exists given a decimal string
=> fix(ExitCode): add from_str in ExitCode and replace parse_no_raise with it, warn if the error code is not in range

commitizen/commands/init.py
=> fix(Init): fix a typo in _ask_version_provider options and remove unnecessary filter

docs/config.md
=> docs(config.md): fix format issue, add period and add title to example config code blocks

commitizen/changelog.py, commitizen/git.py
=> refactor(changelog): shorten generate_tree_from_commits and use set to check used tags

commitizen/cli.py, commitizen/commands/check.py, commitizen/git.py, docs/commands/check.md, tests/commands/test_check_command/test_check_command_shows_description_when_use_help_option.txt, tests/test_git.py
Related PR: #1400 
Wait for #1472 and #1457
Related issue: #1498 
- Added `cz check --default-range`.
=> feat: add check against default branch

tests/commands/test_changelog_command.py
This PR adds a test to ensure the `_export_template` method raises a `NotAllowed` exception when the changelog template has no filename.
Related Code Fix PR: https://github.com/commitizen-tools/commitizen/pull/1550
Close #1503
=> test(changelog): ensure error on missing changelog template filename

poetry.lock, pyproject.toml
It was not caught by CI as it's part of the test group. Will need to do a hot fix and yank 4.9.0
>
> ```text
> ```
=> fix(dependency): move deprecated to project.dependencies

tests/commands/test_init_command.py
=> test(Init): add type hint and rename variable

tests/commands/test_changelog_command.py
I just found that those lines can be removed and tests still passes.
>
> ```text
> ```
=> test(changelog): remove unused timer fixture
