pyproject.toml
=> fix: #28 allows poetry add on py36 envs

pyproject.toml
after questionary 1.4, we can modify the style of prompt and highlighted text at the same time
#37
=> build(poetry): update questionary version to ^1.4

.github/workflows/pythonpackage.yml, commitizen/commands/commit.py, scripts/test
There were problems with travis so I'm moving to github actions
=> ci: new github actions

commitizen/commands/bump.py, tests/test_bump_command.py
"poetry run pytest" on windows will now complete without this error.
=> fix: issue 67: shutil.py:606: PermissionError

README.rst
Fixes #70.
Also my editor (vim) adds a trailing new line at end of document, hope this is not a problem.
=> Correct typo to spell "convention"

commitizen/commands/bump.py
=> correcting style mistake

commitizen/commands/bump.py, commitizen/config.py, commitizen/defaults.py, docs/config.md, tests/test_conf.py
=> Deprecation warning for config through ini files

docs/check.md, docs/index.md, mkdocs.yml
add the documentation for the check command in the docs directory
=> docs(check): check documentation

docs/bump.md
modify typo in bump command docs, path should be corrected as patch.
=> docs(bump): modify typo in bump command docs

commitizen/cli.py, commitizen/config.py
=> Fix config name overwritten error

docs/customization.md
=> docs(customization): add cookiecutter template to doc

.github/workflows/pythonpackage.yml, scripts/test
=> fix(scripts/test): ensure the script fails once the first failure happens

.pre-commit-hooks.yaml, docs/check.md
Add hook for [pre-commit](https://pre-commit.com/)
=> Add pre commit hook

commitizen/cli.py
=> fix(cli): fix name cannot be overwritten through config in newly refactored config design

.github/workflows/pythonpublish.yaml, scripts/publish
=> use peaceiris/actions-gh-pages@v2 to publish docs

.github/workflows/docspublish.yaml, .github/workflows/pythonpublish.yaml
=> ci: separate docs from python publishing

docs/external_links.md, mkdocs.yml
(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)
-  [x] **Documentation Update**
**Describe what the change is**
```sh
mkdocs serve
http://127.0.0.1:8000/external_links/
```
External Links page exists
If applicable, reference to the issue related to this pull request.
#208
=> docs(external_links): add talks, articles section to external_links

docs/check.md
Expands on the different use cases for using `cz check` as well
Expands on cz check docs, more specifically the `--rev-range` option
https://github.com/commitizen-tools/commitizen/issues/227
=> Add `cz check --rev-range` to the docs

docs/README.md
Correct link to docs in README
Closes #245
=> docs(README): fix link to documentation

commitizen/cz/conventional_commits/conventional_commits.py
=> fix: conventional commit schema

.github/workflows/bumpversion.yml, docs/tutorials/github_actions.md, docs/tutorials/gitlab_ci.md, docs/tutorials/jenkins_pipeline.md, mkdocs.yml
- Add new tutorial about jenkins
- Update old tutorials
- Attempt to fix publishing issue by adding token on checkout
=> 78 jenkins ci

docs/tutorials/github_actions.md
=> docs: correct markdown on github actions tutorial page

docs/third-party-commitizen.md
Add cz_legacy to 3rd party section. Sidequest of #319
1. `poetry run mkdocs serve`
2. Go to http://127.0.0.1:8000/third-party-commitizen/
N/A
=> Add cz_legacy to 3rd party section

.github/workflows/homebrewpublish.yaml
Reading the docs from the action it says that it may have issues if running on ubuntu. 
I thought it would be nice to run on macos and see if it works
https://github.com/dawidd6/action-homebrew-bump-formula
=> ci: attempt to fix homebrew action

docs/faq.md
=> docs: correct title in faq

docs/tutorials/github_actions.md
=> docs(tutorial/github_action): explain how to create a github release

pyproject.toml
=> ci: update package version in pyproject.toml

docs/contributing.md
Update contribution guidelines
=> docs(contributing): do not request modifications to changelog

docs/external_links.md
as title
render the link to freecode camp documentation in Resources section
1. poetry run mkdocs serve
2. open `http://127.0.0.1:8000`
=> add freecode camp tutorial to documentation

commitizen/config/toml_config.py, docs/faq.md
=> docs(faq.md): close parentheses

commitizen/bump.py, commitizen/commands/changelog.py, commitizen/commands/commit.py, commitizen/commands/init.py, commitizen/config/json_config.py, commitizen/config/yaml_config.py, commitizen/git.py, tests/test_git.py
Determine the newline character to write with `git config core.eof`.
It will adopt the newline character from the configuration key `core.elf` of Git while writing to any file.
See tests.
Help me cc [CanisHelix](https://github.com/CanisHelix) check this commit. Thanks!
=> feat: determine newline to write with Git

docs/README.md
This fixes a typo in the pre-commit install command
=> fix(README.md): fix pre-commit install command

pyproject.toml
Closes #588 
Allow for installation of argcomplete 2.0.x in commitizen enabled projects
=> Relax specification for argcomplete dependency

.github/workflows/pythonpackage.yml
as title
be able to run CI manually on github
=> ci(github-actions): add workflow-dispatch for manually trigger CI check

docs/contributing.md
update the contributing.md, to add jpg
the PR is only about doc update.
to build the doc by command below
poetry run mkdocs build
=> docs(docs/contributing.md): udpate steps to contribute, add gpg

commitizen/commands/init.py
Correct spelling in the pre-commit init failure message
Error message will be spelled correctly.
NA
=> chore: fix error message typo

commitizen/version_schemes.py, poetry.lock, pyproject.toml
Upgrade mypy, ruff and fix style failure due to upgraded version
close https://github.com/commitizen-tools/commitizen/pull/761, https://github.com/commitizen-tools/commitizen/pull/762, https://github.com/commitizen-tools/commitizen/pull/763, https://github.com/commitizen-tools/commitizen/pull/763, https://github.com/commitizen-tools/commitizen/pull/766, https://github.com/commitizen-tools/commitizen/pull/761
everything should work as it used to be
./scripts/test
=> Upgrade mypy

.github/workflows/bumpversion.yml, docs/README.md
=> fix: add sponsors to README

CHANGELOG.md
somehow, our tags were messed up. there were 2 tags each version (e.g., `v3.12.0`, `3.12.0`). some of them were even on different commits. I tried to clean them up and this PR is intended to cleanup the changelog as well
=> docs(changelog): remove duplicate versions

.github/workflows/label_pr.yml
=> ci(github-actions): fix labeler typo

docs/bump.md
Simple typo fix in documentation for `bump` command.
=> docs(bump): Fix typo in documentation

.github/CODEOWNERS
as title, our original format is wrong and does not work
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> ci(github): fix codeowners format

.github/workflows/docspublish.yml
this has been changed since 3.0 as well
https://github.com/peaceiris/actions-gh-pages/issues/123
=> ci(github-actions): replace env with "with" for docpublish aciton

.github/workflows/docspublish.yml
=> ci(github-actions): update peaceiris/actions-gh-pages to v4

docs/getting_started.md
Update the "getting_started" document by changing "version type" to "version scheme." Additionally, fix the broken link by redirecting that to the "version_scheme" section.
Close: #1008
=> docs(getting_started): fix broken link

pyproject.toml
Close: https://github.com/commitizen-tools/commitizen/issues/1368
=> build(pyproject.toml): fix license metadata

.github/ISSUE_TEMPLATE/bug_report.yml
Closes #1134
Remove outdated description in `bug_report.yml`.
I tested the new template on my own repo.
New Bug Report issue template should look like:
After copying and pasting the output:
Preview mode:
NA
NA
=> docs(bug_report.yml): update bug_report.yml

tests/test_changelog.py
=> test(changelog): code cleanup and better type

commitizen/commands/check.py
=> refactor(check): code cleanup

commitizen/version_schemes.py
=> refactor(version_scheme): cleanup

docs/faq.md
Closes #1129
Address the issue and add a link to our issue tracker with filters.
=> docs(faq): add "features we won't add" section

commitizen/config/json_config.py, commitizen/config/toml_config.py, commitizen/config/yaml_config.py, poetry.lock, pyproject.toml
Resolves #1476 
- #1476
>
> ```text
> ```
=> build(deps-dev): bump mypy to 1.16.0

.github/pull_request_template.md
Make the following change in PR template:
```
```
=> docs(pull_request_template): add task to fix broken external links in the docs

commitizen/cli.py
=> refactor(ParseArgs): simplify `__call__` function body

commitizen/providers/scm_provider.py
=> refactor(ScmProvider): replace sorted with max

commitizen/git.py
=> refactor(git): remove redundant if branch

commitizen/commands/bump.py
=> fix(Bump): rewrite --get-next NotAllowed error message for consistency

commitizen/commands/init.py
=> fix(init): make welcome message easier to read
